const ATTRS=['火','水','風','火水','水風','火風','全'];
const A={火:{火:2/3,水:1/3,風:1,火水:1/2,水風:2/3,火風:5/6,全:2/3},水:{火:1,水:2/3,風:1/3,火水:5/6,水風:1/2,火風:2/3,全:2/3},風:{火:1/3,水:1,風:2/3,火水:2/3,水風:5/6,火風:1/2,全:2/3},火水:{火:5/6,水:1/2,風:2/3,火水:2/3,水風:7/12,火風:3/4,全:2/3},水風:{火:2/3,水:5/6,風:1/2,火水:3/4,水風:2/3,火風:7/12,全:2/3},火風:{火:1/2,水:2/3,風:5/6,火水:7/12,水風:3/4,火風:2/3,全:2/3},全:{火:2/3,水:2/3,風:2/3,火水:2/3,水風:2/3,火風:2/3,全:2/3}};
let chars=[],tierData=null,current=null,pickerTarget=null,selected={attacker:null,defender:null},skillOn={attacker:false,defender:false};
const $=id=>document.getElementById(id);
window.addEventListener('DOMContentLoaded',()=>{ATTRS.forEach(x=>{$('attackerAttribute').add(new Option(x,x));$('defenderAttribute').add(new Option(x,x))});bind();loadData();calculate()});
function bind(){$('menuToggle').onclick=()=> $('sidebar').classList.toggle('open');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('openOpinion').onclick=()=>openModal('opinion');$('attackerPicker').onclick=()=>openPicker('attacker');$('defenderPicker').onclick=()=>openPicker('defender');$('swap').onclick=swap;$('zkSearch').oninput=()=>renderGrid($('zkBox'),$('zkSearch').value,false);$('pickerSearch').oninput=()=>renderGrid($('pickerGrid'),$('pickerSearch').value,true);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('#detailActions button').forEach(b=>b.onclick=()=>chooseCurrent(b.dataset.role));['attackerPower','defenderHp','attackerAttribute','defenderAttribute','attackBoosts','cutRates'].forEach(id=>$(id).addEventListener('input',calculate));$('attackerSkillBtn').onclick=()=>toggleSkill('attacker');$('defenderSkillBtn').onclick=()=>toggleSkill('defender');$('tierBtn').onclick=execTier;$('opinionSubmit').onclick=submitOpinion;}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(innerWidth<801)$('sidebar').classList.remove('open');scrollTo(0,0)}
function openModal(id){$(id).hidden=false}function closeModal(id){$(id).hidden=true}
async function loadData(){try{chars=await fetch('zukan_beta.json').then(r=>r.json());$('zkStatus').textContent='全'+chars.length+'体';renderGrid($('zkBox'),'',false)}catch(e){$('zkStatus').textContent='図鑑データを読み込めませんでした'}try{tierData=await fetch('tier_all_patterns.json').then(r=>r.json());Object.entries(tierData.meta.shibari).forEach(([id,n])=>$('attribute').add(new Option(n,id)))}catch(e){} }
function renderGrid(box,q,picking){q=(q||'').trim().toLowerCase();box.innerHTML='';chars.filter(c=>!q||(c.name||'').toLowerCase().includes(q)).forEach(c=>{let b=document.createElement('button');b.className='zk-card';b.innerHTML='<img src="'+esc(c.imageUrl||'')+'"><small>'+esc(c.name||'')+'</small>';b.onclick=()=>openDetail(c,picking);box.appendChild(b)})}
function openPicker(role){pickerTarget=role;$('pickerTitle').textContent=(role==='attacker'?'攻撃キャラ':'攻撃対象キャラ')+'を選択';$('pickerSearch').value='';renderGrid($('pickerGrid'),'',true);openModal('picker')}
function openDetail(c,picking=false){current=c;let d=c.details||{};$('detailImage').src=c.imageUrl||'';$('detailName').textContent=c.name||d.name||'';$('detailMeta').textContent=[d.rare,d.attribute].filter(Boolean).join(' / ');$('detailStats').innerHTML=[['Cost',d.cost],['無凸HP',d.hp],['無凸Power',d.power],['完凸HP',d.limitHp],['完凸Power',d.limitPower]].filter(x=>x[1]!=null&&x[1]!=='').map(x=>'<div><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('');$('detailSkill').textContent=d.skill||'スキルなし';document.querySelector('[data-role="attacker"]').hidden=picking;document.querySelector('[data-role="defender"]').hidden=picking;document.querySelector('[data-role="picker"]').hidden=!picking;openModal('detail')}
function chooseCurrent(role){if(role==='picker')role=pickerTarget;if(!role||!current)return;setCharacter(role,current);closeModal('detail');closeModal('picker');showPage('calculator')}
function setCharacter(role,c){selected[role]=c;skillOn[role]=false;let d=c.details||{},pick=$(role+'Picker');pick.querySelector('.character-image').style.backgroundImage='url("'+(c.imageUrl||'')+'")';pick.querySelector('strong').textContent=c.name||'';pick.querySelector('small').textContent=[d.rare,d.attribute].filter(Boolean).join(' / ');$(role==='attacker'?'attackerPower':'defenderHp').value=Number(role==='attacker'?(d.limitPower??d.power??0):(d.limitHp??d.hp??0));$(role+'Attribute').value=normalizeAttr(d.attribute);$(role+'Skill').textContent=d.skill||'スキルなし';$(role+'SkillBtn').disabled=!d.skill;$(role+'SkillBtn').textContent='スキル使用';calculate()}
function normalizeAttr(x){let s=String(x||'');return ATTRS.find(a=>s===a)||ATTRS.filter(a=>a!=='全').sort((a,b)=>b.length-a.length).find(a=>s.includes(a))||'全'}
function swap(){let a=selected.attacker,d=selected.defender,as=skillOn.attacker,ds=skillOn.defender;if(d)setCharacter('attacker',d);else clearRole('attacker');if(a)setCharacter('defender',a);else clearRole('defender');skillOn.attacker=ds;skillOn.defender=as;syncSkill('attacker');syncSkill('defender');calculate()}
function clearRole(role){selected[role]=null;skillOn[role]=false;let p=$(role+'Picker');p.querySelector('.character-image').style.backgroundImage='';p.querySelector('strong').textContent='未選択';p.querySelector('small').textContent='タップして図鑑から選択';$(role==='attacker'?'attackerPower':'defenderHp').value=0;$(role+'Skill').textContent='キャラ未選択';$(role+'SkillBtn').disabled=true}
function toggleSkill(role){skillOn[role]=!skillOn[role];syncSkill(role);calculate()}function syncSkill(role){$(role+'SkillBtn').textContent=skillOn[role]?'スキル解除':'スキル使用'}
function nums(s){return String(s||'').split(',').map(Number).filter(Number.isFinite)}function calcCuts(rates){return rates.sort((a,b)=>b-a).reduce((m,s,i)=>m*(1-(s/100)*3/(2*(i+1)+1)),1)}
function calculate(){let p=Math.max(0,+$('attackerPower').value||0),hp=Math.max(0,+$('defenderHp').value||0),boost=nums($('attackBoosts').value).reduce((m,x)=>m*(1+x/100),1),cuts=calcCuts(nums($('cutRates').value)),attr=A[$('attackerAttribute').value]?.[$('defenderAttribute').value]??1,base=p*boost*1.944*attr*cuts;let min=Math.floor(base*.9),mid=Math.floor(base),max=Math.floor(base*1.1);$('damageMin').textContent=min.toLocaleString();$('damageBase').textContent=mid.toLocaleString();$('damageMax').textContent=max.toLocaleString();$('killResult').textContent=p&&hp?(mid>=hp?'基準ダメージで撃破可能':'基準ダメージでは残りHP '+(hp-mid).toLocaleString()):'数値を入力してください';renderGhost(hp)}
function renderGhost(hp){if(!hp){$('ghostResult').textContent='攻撃対象のHPを入力してください';return}let ds=[['最大ダメージ',Math.floor(1000*1.944*(2/3)*1.1)],['基準ダメージ',Math.floor(1000*1.944*(2/3))],['最小ダメージ',Math.floor(1000*1.944*(2/3)*.9)]];$('ghostResult').innerHTML='<div class="ghost-grid">'+ds.map(([n,d])=>{let kill=Math.ceil(hp/d);return '<div><b>'+n+' '+d.toLocaleString()+'</b><br>'+(kill-1)+'発耐える / '+kill+'発目で撃破</div>'}).join('')+'</div>'}
function execTier(){if(!tierData){$('tierResult').textContent='Tierデータを読み込めませんでした';return}let hv=$('hosei').value,key=($('attribute').value||'*')+'|'+($('cost').value||'*')+'|'+($('waku').value||'*')+'|'+(hv===''?'*':hv),bucket=tierData.data[key];if(!bucket){$('tierResult').textContent='該当データなし';return}let mode=$('mode').value,min=+$('minCount').value,arr=Object.entries(bucket).map(([id,d])=>({id:+id,count:d[0],rate:d[0]?d[1]/d[0]:0})).filter(x=>x.count>=min).sort((a,b)=>mode==='使用者数'?b.count-a.count:b.rate-a.rate),max=arr[0]?.count||0,ths=mode==='使用者数'?[max/2,max/3,max/4,max/5,max/6,max/7,max/8,0]:[.4,.25,.1,0,-.1,-.25,-.4,-Infinity],names=['S','A','B','C','D','E','F','G'],groups=names.map(()=>[]);arr.forEach(x=>{let v=mode==='使用者数'?x.count:x.rate;groups[ths.findIndex(t=>v>=t)].push(x.id)});$('tierResult').innerHTML=groups.map((g,i)=>g.length?'<div class="tier-row"><b>'+names[i]+'</b><div class="tier-icons">'+g.map(id=>{let c=chars.find(x=>+x.id===id);return c?'<img data-id="'+id+'" src="'+esc(c.imageUrl||'')+'">':''}).join('')+'</div></div>':'').join('');$('tierResult').querySelectorAll('[data-id]').forEach(im=>im.onclick=()=>{let c=chars.find(x=>+x.id===+im.dataset.id);if(c)openDetail(c,false)})}
const OPINION_URL='https://script.google.com/macros/s/AKfycbzb1SZylMA0l61jgM628eMbXeUt7M4tVx-BrrOIK3KpvAWZ_WzJR_cSPsdOMA5EETt8/exec';function submitOpinion(){let t=$('opinionText').value.trim();if(!t){$('opinionMsg').textContent='内容を入力してください';return}$('opinionSubmit').disabled=true;$('opinionMsg').textContent='送信中...';fetch(OPINION_URL+'?api=opinion&text='+encodeURIComponent(t)).then(r=>{if(!r.ok)throw Error();$('opinionText').value='';$('opinionMsg').textContent='送信しました'}).catch(()=>$('opinionMsg').textContent='送信に失敗しました').finally(()=>$('opinionSubmit').disabled=false)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
