/* 英語物語 対戦ツール: calculator */
function toggleDetailMode(){detailMode=!detailMode;syncDetailMode();calculate()}
function syncDetailMode(){let b=$('detailMode');if(b){b.textContent=detailMode?'詳細モード ON':'詳細モード OFF';b.setAttribute('aria-pressed',String(detailMode))}document.querySelectorAll('.detail-mode-target').forEach(x=>x.classList.toggle('detail-mode-hidden',!detailMode))}
function resetProgressive(prefix,count){for(let i=1;i<=count;i++){let q=$(prefix+i);if(q)q.value=''}progress(prefix,count)}
function resetExceptCharacter(r){skillEnabled[r]=false;clearBorrowedSkills(r);syncSkill(r);if(r==='attacker'){$('answerSpeed').value='1.2';$('selfMode').value='1.2';$('questionLevel').value='1.8';$('survivalTurns').value='0';$('allAttack').value='0';resetProgressive('attackBuffRate',4);resetProgressive('extraHit',3)}else{resetProgressive('cutRate',6);resetProgressive('extraHeal',3)}calculate()}
function removeCharacter(r){selected[r]=null;skillEnabled[r]=false;let p=$(r+'Picker');p.querySelector('.portrait').style.backgroundImage='';p.querySelector('strong').textContent='未選択';p.querySelector('small').textContent='タップして図鑑から選択';$(r==='attacker'?'attackerPower':'defenderHp').value=0;$(r+'Attribute').value='火';$(r+'Event').value='1';$(r+'Skill').textContent='キャラ未選択';$(r+'SkillBtn').disabled=true;syncSkill(r);calculate()}
function resetAll(){detailMode=false;syncDetailMode();removeCharacter('attacker');removeCharacter('defender');resetExceptCharacter('attacker');resetExceptCharacter('defender');$('mode').selectedIndex=0;$('attribute').selectedIndex=0;$('cost').selectedIndex=0;$('waku').selectedIndex=0;$('hosei').value='0';$('minCount').value='10';$('tierResult').innerHTML='';calculate()}
function swap(){let a=selected.attacker,d=selected.defender,as=skillEnabled.attacker,ds=skillEnabled.defender;if(d){skillEnabled.attacker=ds;setCharacter('attacker',d,true)}if(a){skillEnabled.defender=as;setCharacter('defender',a,true)}}
function toggleSkill(r){skillEnabled[r]=!skillEnabled[r];syncSkill(r);calculate()}
function syncSkill(r){let b=$(r+'SkillBtn');b.textContent=skillEnabled[r]?'スキル解除':'スキル使用';b.classList.toggle('active',skillEnabled[r])}
function raw(v){let n=parseFloat(String(v??'').replace('%',''));return Number.isFinite(n)?n:NaN}
function en(e){let n=String(e?.effect??e?.['スキル効果']??'').trim();if(['被ダメージ減少','ダメージカット','シールド'].includes(n))return'シールド';if(['攻撃集中','集中','かばう'].includes(n))return'集中';if(n==='かわす')return'かわす';if(['攻撃力アップ','攻撃力増加','攻撃力上昇'].includes(n))return'攻撃力アップ';if(['属性変更','属性変化','色変'].includes(n))return'色変';if(['連続攻撃','連撃'].includes(n))return'連撃';return n}
function amt(e){let n=raw(e?.value??e?.amount??e?.['効果量']);return ['シールド','集中','かわす','攻撃力アップ','回復'].includes(en(e))&&Number.isFinite(n)&&Math.abs(n)<=10?n*100:n}
function effectEntries(r){let out=[],own=selected[r]?.details?.skillEffects;if(skillEnabled[r]&&Array.isArray(own))own.forEach(effect=>out.push({effect,borrowed:false}));for(let i=0;i<(borrowedSkills[r]||[]).length;i++){if(!borrowedEnabled[r]?.[i])continue;let list=borrowedSkills[r][i]?.details?.skillEffects;if(Array.isArray(list))list.forEach(effect=>out.push({effect,borrowed:true}))}return out}
function effectScope(e){return canon(e?.applier??e?.['適用者']??'')}
function conditionAttribute(value){let s=canon(value);if(!s||['自身','自分','全員','味方全員','リーダー','敵全員','すべて','全'].includes(s))return null;return ATTRS.filter(a=>a!=='全').sort((a,b)=>b.length-a.length).find(a=>s.includes(a))||null}
function matches(cur,req){req=conditionAttribute(req);if(!req)return true;cur=canon(cur);if(cur==='全')return true;return ['火水','水風','風火'].includes(req)?cur===req:cur.includes(req)}
function applierMatches(e,own,borrowed){let scope=effectScope(e);if(['自身','自分','リーダー','全員','味方全員','すべて','全',''].includes(scope))return true;return matches(own,e?.applierAttribute??e?.['適用者属性']??scope)}
function targetMatches(e,opponent){let target=e?.targetAttribute??e?.['対象者属性']??e?.target??e?.['対象者'];return matches(opponent,target)}
function appliesEntry(entry,own,opponent){return applierMatches(entry.effect,own,entry.borrowed)&&targetMatches(entry.effect,opponent)}
function applies(e,own,opponent){return appliesEntry({effect:e,borrowed:false},own,opponent)}
function colorValue(e){let v=canon(e?.value??e?.amount??e?.['効果量']);return ATTRS.includes(v)?v:null}
function skillState(a,d,h){let o={a,d,atk:1,hits:1,cuts:[],healRates:[],all:false,concentration:false,al:[],dl:[]};for(let r of ['attacker','defender'])for(let entry of effectEntries(r)){let e=entry.effect;if(en(e)!=='色変')continue;let own=r==='attacker'?o.a:o.d,opp=r==='attacker'?o.d:o.a;if(!appliesEntry(entry,own,opp))continue;let v=colorValue(e);if(v)r==='attacker'?o.a=v:o.d=v}for(let r of ['attacker','defender']){let own=r==='attacker'?o.a:o.d,opp=r==='attacker'?o.d:o.a,lab=r==='attacker'?o.al:o.dl;for(let entry of effectEntries(r)){let e=entry.effect,n=en(e);if(!n)continue;if(!appliesEntry(entry,own,opp)){lab.push(n+'：条件不成立');continue}if(n==='色変'){let v=colorValue(e);lab.push(v?`属性を${v}に変更`:'属性変更：データ確認必要');continue}if(['遅延','短縮','蘇生'].includes(n)){lab.push(n+'：計算対象外');continue}let v=amt(e);if(n==='攻撃力アップ'&&r==='attacker'&&Number.isFinite(v)){o.atk*=1+v/100;lab.push(`攻撃力+${fmt(v)}%`)}else if(n==='連撃'&&r==='attacker'){let q=Math.max(1,Math.floor(raw(e.value??e.amount)));o.hits+=q-1;lab.push(`${q}回連撃`)}else if(n==='全体攻撃'&&r==='attacker'){o.all=true;lab.push('全体攻撃×5')}else if(['シールド','集中','かわす'].includes(n)&&r==='defender'&&Number.isFinite(v)){o.cuts.push(v);if(n==='集中'||n==='かわす')o.concentration=true;lab.push(`${fmt(v)}%軽減`)}else if(n==='回復'&&r==='defender'&&Number.isFinite(v)){o.healRates.push(v);lab.push(`回復${fmt(v)}%（最大HPまでは等倍、超過分は1/2）`)}else if(!['攻撃力アップ','連撃','全体攻撃','シールド','集中','かわす','回復'].includes(n)){lab.push(n+'：計算対象外')}}}return o}
function vals(p){return Array.from({length:fieldCount(p)},(_,i)=>raw($(p+(i+1))?.value)).filter(Number.isFinite)}
function amul(){return vals('attackBuffRate').reduce((m,v)=>m*(1+v/100),1)}
function cmul(a){return a.map(v=>Math.max(0,Math.min(100,v))).sort((x,y)=>y-x).reduce((m,v,i)=>m*(1-v/100*3/(2*(i+1)+1)),1)}
function manualHits(){return vals('extraHit').reduce((sum,v)=>sum+Math.max(0,Math.floor(v)-1),0)}
function healAdded(currentHp,maxHp,rates){maxHp=Math.max(0,maxHp||currentHp);let raw=rates.reduce((sum,v)=>sum+maxHp*Math.max(0,v)/100,0),gap=Math.max(0,maxHp-currentHp);return Math.floor(Math.min(raw,gap)+Math.max(0,raw-gap)*.5)}
function calculate(){
  if(typeof calculatorRefreshStyledSelects==='function')calculatorRefreshStyledSelects();
  let p=Math.max(0,+$('attackerPower').value||0),baseHp=Math.max(0,+$('defenderHp').value||0),eventMul=+$('defenderEvent').value||1,hp=baseHp*eventMul,maxBase=Number(selected.defender?.details?.limitHp??selected.defender?.details?.hp??baseHp),maxHp=Math.max(hp,maxBase*eventMul),s=skillState($('attackerAttribute').value,$('defenderAttribute').value,hp),healRates=s.healRates.concat(detailMode?vals('extraHeal'):[]),eh=hp+healAdded(hp,maxHp,healRates),rt=MATCH[s.a]?.[s.d]??1,sur=detailMode?1.3**(+$('survivalTurns').value||0):1,hits=s.hits+(detailMode?manualHits():0),manualCuts=vals('cutRate'),allRequested=$('allAttack').value==='1'||s.all===true,missingCover=allRequested&&!s.concentration&&manualCuts.length===0,all=allRequested?5:1,attackerBase=p*(+$('answerSpeed').value||1)*(+$('selfMode').value||1)*(+$('attackerEvent').value||1)*(+$('questionLevel').value||1)*sur*amul()*s.atk*.75,cutMultiplier=cmul(manualCuts.concat(s.cuts)),base=attackerBase*cutMultiplier*all,perHit=base*rt,b=perHit*hits,mn=Math.floor(b*.9),mx=Math.floor(b*1.1),mp=eh?Math.floor(mn/eh*100):0,xp=eh?Math.floor(mx/eh*100):0,st=!p||!eh?'数値を入力してください':mn>=eh?'確定撃破':mx>=eh?'乱数撃破':'撃破不可',durability=cutMultiplier?Math.floor(eh/cutMultiplier):0;
  $('attackerEffect').textContent=s.al.join('・');$('defenderEffect').textContent=s.dl.join('・');$('killResult').textContent=st;$('damageRange').textContent=`${mn.toLocaleString()}～${mx.toLocaleString()}（${mp}%～${xp}%）`;$('durabilityValue').textContent=durability.toLocaleString();
  let remaining='';if(eh&&st==='乱数撃破')remaining=`残りHP 0～${Math.max(0,Math.floor(eh-mn)).toLocaleString()}`;else if(eh&&st==='撃破不可')remaining=`残りHP ${Math.max(0,Math.ceil(eh-mx)).toLocaleString()}～${Math.max(0,Math.ceil(eh-mn)).toLocaleString()}`;$('remainingHp').textContent=remaining;
  let hitInfo='',killLabel='',spareLabel='';if(hits>1&&eh&&mx>=eh){let minPerHit=Math.floor(perHit*.9),maxPerHit=Math.floor(perHit*1.1),first=Math.min(hits,Math.ceil(eh/maxPerHit)),last=Math.min(hits,Math.ceil(eh/minPerHit)),kill=first===last?`${first}発で撃破`:`${first}～${last}発で撃破`,spareMin=Math.max(0,hits-last),spareMax=Math.max(0,hits-first);killLabel=kill;if(spareMax>0){let spareHits=spareMin===spareMax?`${spareMin}発`:`${spareMin}～${spareMax}発`,sparePerHit=attackerBase*(MATCH[s.a]?.['全']??2/3),spareDamageMin=Math.floor(sparePerHit*.9*spareMin),spareDamageMax=Math.floor(sparePerHit*1.1*spareMax);spareLabel=`余剰火力（属性相性 2/3）: ${spareHits}（${spareDamageMin.toLocaleString()}～${spareDamageMax.toLocaleString()}）`+(allRequested?' ×全体':'')}hitInfo=`${kill}${spareLabel?`<br><small>${spareLabel}</small>`:''}`}
  $('multiHitResult').innerHTML=hitInfo;$('allAttackWarning').textContent=missingCover?'全体スキルが使用されています。引き継いだ庇うスキルの効果量を追加軽減率として入力し忘れていませんか？':'';lastResult={st,mn,mx,mp,xp,eh,s,allApplied:allRequested,killLabel,spareLabel,remaining,durability,detailMode};renderGhost(eh)
}

function renderGhost(h){if(!h){$('ghostResult').textContent='攻撃対象のHPを入力してください';ghostData=null;return}let b=1296,mn=Math.floor(b*.9),mx=Math.floor(b*1.1),first=Math.ceil(h/mx),last=Math.ceil(h/mn);ghostData={survive:`${Math.max(0,first-1)}～${Math.max(0,last-1)}発耐え`,kill:`${first}～${last}発目で撃破される`};$('ghostResult').innerHTML=`<div><b>${ghostData.survive}</b></div><div><b>${ghostData.kill}</b></div>`}
function pickerImageUrl(role){let bg=$(role+'Picker').querySelector('.portrait').style.backgroundImage;return bg&&bg!=='none'?bg.slice(5,-2):''}
function portraitElement(role){return $(role+'Picker').querySelector('.portrait')}
function imageUrlCandidates(url){let a=[url];try{let u=new URL(url),m;if(u.hostname==='drive.google.com'&&(m=u.pathname.match(/\/file\/d\/([^/]+)/)))a.unshift('https://lh3.googleusercontent.com/d/'+m[1]);if(u.hostname==='github.com'&&u.pathname.includes('/blob/'))a.unshift(url.replace('https://github.com/','https://raw.githubusercontent.com/').replace('/blob/','/'));if(u.hostname.endsWith('githubusercontent.com'))a.unshift(url)}catch{}return[...new Set(a.filter(Boolean))]}
async function loadImg(url){for(let candidate of imageUrlCandidates(url)){try{let res=await fetch(candidate,{mode:'cors',cache:'force-cache',credentials:'omit'});if(!res.ok)continue;let blob=await res.blob(),objectUrl=URL.createObjectURL(blob),im=await new Promise((resolve,reject)=>{let x=new Image;x.onload=()=>resolve(x);x.onerror=reject;x.src=objectUrl});URL.revokeObjectURL(objectUrl);return im}catch{}try{let im=await new Promise((resolve,reject)=>{let x=new Image;x.crossOrigin='anonymous';x.referrerPolicy='no-referrer';x.onload=()=>resolve(x);x.onerror=reject;x.src=candidate});return im}catch{}}return null}
function wrapCanvasText(x,text,left,y,maxWidth,lineHeight,maxLines=3){let line='',lines=[];for(let ch of String(text||'')){if(x.measureText(line+ch).width>maxWidth&&line){lines.push(line);line=ch;if(lines.length===maxLines-1)break}else line+=ch}if(line&&lines.length<maxLines)lines.push(line);for(let s of lines){x.fillText(s,left,y);y+=lineHeight}return y}
function drawImageCover(x,img,left,top,size){x.save();x.fillStyle='#f1f3f5';x.fillRect(left,top,size,size);if(img){let scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;x.drawImage(img,left+(size-w)/2,top+(size-h)/2,w,h)}else{x.fillStyle='#6b7280';x.font='16px sans-serif';x.textAlign='center';x.fillText('画像読込不可',left+size/2,top+size/2+6)}x.restore()}
function appliedEffectLabels(role,state,effectList,borrowed=false){let out=[],own=role==='attacker'?state.a:state.d,opp=role==='attacker'?state.d:state.a;for(let e of effectList||[]){if(!appliesEntry({effect:e,borrowed},own,opp))continue;let n=en(e),v=amt(e);if(n==='攻撃力アップ'&&role==='attacker'&&Number.isFinite(v))out.push(`攻撃力+${fmt(v)}%`);else if(n==='連撃'&&role==='attacker')out.push(`${Math.max(1,Math.floor(raw(e.value??e.amount)))}回連撃`);else if(n==='全体攻撃'&&role==='attacker')out.push('全体攻撃×5');else if(['シールド','集中','かわす'].includes(n)&&role==='defender'&&Number.isFinite(v))out.push(`${fmt(v)}%軽減`);else if(n==='回復'&&role==='defender'&&Number.isFinite(v))out.push(`回復${fmt(v)}%`);else if(n==='色変'){let c=colorValue(e);if(c)out.push(`属性を${c}に変更`)}}return out}
function ownAppliedLabels(role,state){return skillEnabled[role]?appliedEffectLabels(role,state,selected[role]?.details?.skillEffects):[]}
function borrowedAppliedLabels(role,state){let out=[];for(let i=0;i<(borrowedSkills[role]||[]).length;i++)if(borrowedEnabled[role]?.[i])out.push(...appliedEffectLabels(role,state,borrowedSkills[role][i]?.details?.skillEffects,true));return out}
async function createResultImage(){if(!lastResult)return null;let[ai,di]=await Promise.all([loadImg(selected.attacker?.imageUrl||pickerImageUrl('attacker')),loadImg(selected.defender?.imageUrl||pickerImageUrl('defender'))]);let scale=2,c=document.createElement('canvas'),x=c.getContext('2d');c.width=1400*scale;c.height=1080*scale;x.scale(scale,scale);x.fillStyle='#fff';x.fillRect(0,0,1400,1080);x.textBaseline='alphabetic';x.fillStyle='#222';x.textAlign='center';x.font='700 34px sans-serif';x.fillText('ダメージ計算結果',700,54);drawSide(x,'攻撃キャラ',selected.attacker,'attacker',ai,45,85);drawSide(x,'攻撃対象キャラ',selected.defender,'defender',di,710,85);x.strokeStyle='#ddd';x.strokeRect(45,875,1310,155);x.fillStyle='#e53935';x.font='700 34px sans-serif';x.fillText(lastResult.st,700,915);x.fillStyle='#3f4b59';x.font='700 20px sans-serif';if(lastResult.killLabel)x.fillText(lastResult.killLabel,700,947);x.fillStyle='#66717f';x.font='600 16px sans-serif';if(lastResult.spareLabel)x.fillText(lastResult.spareLabel,700,973);x.fillStyle='#222';x.font='700 24px sans-serif';x.fillText(`${lastResult.mn.toLocaleString()}～${lastResult.mx.toLocaleString()}（${lastResult.mp}%～${lastResult.xp}%）`,700,1010);try{return c.toDataURL('image/png',1)}catch{return null}}
function resultScreenshotRows(role){
  const attack=role==='attacker',state=lastResult.s,rows=attack?[
    ['Power',$('attackerPower').value],['属性',state.a],['イベント補正',$('attackerEvent').selectedOptions[0]?.textContent],['解答速度',$('answerSpeed').selectedOptions[0]?.textContent],['自力モード',$('selfMode').selectedOptions[0]?.textContent],['問題レベル',$('questionLevel').selectedOptions[0]?.textContent]
  ]:[['HP',$('defenderHp').value],['属性',state.d],['イベント補正',$('defenderEvent').selectedOptions[0]?.textContent],['耐久値',lastResult.durability.toLocaleString()]];
  if(attack&&detailMode)rows.push(['生存補正',$('survivalTurns').selectedOptions[0]?.textContent]);
  vals(attack?'attackBuffRate':'cutRate').forEach((v,i)=>rows.push([attack?'追加攻撃力'+(i+1):'追加軽減率'+(i+1),fmt(v)+'%']));
  if(attack&&detailMode){rows.push(['全体攻撃',lastResult.allApplied?'あり':'なし']);vals('extraHit').forEach((v,i)=>rows.push(['追加連撃効果'+(i+1),fmt(v)+'回']))}
  if(!attack&&detailMode)vals('extraHeal').forEach((v,i)=>rows.push(['追加回復効果'+(i+1),fmt(v)+'%']));
  return rows;
}
function resultScreenshotSide(role){
  const attack=role==='attacker',c=selected[role],section=document.createElement('section');section.className='result-shot-side '+role;
  const title=document.createElement('h3');title.textContent=attack?'攻撃キャラ':'攻撃対象キャラ';section.append(title);
  const identity=document.createElement('div');identity.className='result-shot-identity';const url=c?.imageUrl||pickerImageUrl(role);
  if(url){const img=document.createElement('img');img.src=url;img.alt=c?.name||'';img.referrerPolicy='no-referrer';identity.append(img)}
  const name=document.createElement('strong');name.textContent=c?.name||'未選択';identity.append(name);section.append(identity);
  const grid=document.createElement('dl');grid.className='result-shot-values';for(const [key,value] of resultScreenshotRows(role)){const cell=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value??'';cell.append(dt,dd);grid.append(cell)}section.append(grid);
  const own=skillEnabled[role]?(c?.details?.skill||'スキルなし'):null,ownEffects=ownAppliedLabels(role,lastResult.s),borrowed=borrowedAppliedLabels(role,lastResult.s);
  if(own||borrowed.length){const box=document.createElement('div');box.className='result-shot-skills';const heading=document.createElement('b');heading.textContent='スキル適用';box.append(heading);if(own){const line=document.createElement('p');line.textContent='自キャラ: '+own+(ownEffects.length?' / 効果量: '+ownEffects.join('・'):'');box.append(line)}if(borrowed.length){const line=document.createElement('p');line.textContent='他キャラ: '+borrowed.join('・');box.append(line)}section.append(box)}
  if(!attack&&detailMode&&ghostData){const box=document.createElement('p');box.textContent='幽霊攻撃への耐久: '+ghostData.survive+' / '+ghostData.kill;section.append(box)}return section;
}
function downloadResult(){
  calculate();let overlay=$('resultScreenshot');if(!overlay){overlay=document.createElement('div');overlay.id='resultScreenshot';overlay.className='overlay result-shot-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','スクショ用画面');document.body.append(overlay)}
  overlay.replaceChildren();const panel=document.createElement('div');panel.className='result-shot-panel';const bar=document.createElement('div');bar.className='result-shot-toolbar';const hint=document.createElement('span');hint.textContent='この画面を端末のスクリーンショット機能で保存してください';const close=document.createElement('button');close.type='button';close.textContent='閉じる';close.onclick=()=>{overlay.hidden=true;document.removeEventListener('keydown',onKey)};bar.append(hint,close);
  const sheet=document.createElement('article');sheet.className='result-shot-sheet';const heading=document.createElement('h2');heading.textContent='ダメージ計算結果';sheet.append(heading);const sides=document.createElement('div');sides.className='result-shot-sides';sides.append(resultScreenshotSide('attacker'),resultScreenshotSide('defender'));sheet.append(sides);
  const result=document.createElement('section');result.className='result-shot-verdict';const status=document.createElement('strong');status.textContent=lastResult.st;result.append(status);for(const value of [lastResult.killLabel,lastResult.spareLabel,`${lastResult.mn.toLocaleString()}～${lastResult.mx.toLocaleString()}（${lastResult.mp}%～${lastResult.xp}%）`,lastResult.remaining])if(value){const line=document.createElement('p');line.textContent=value;result.append(line)}sheet.append(result);panel.append(bar,sheet);overlay.append(panel);overlay.hidden=false;
  function onKey(e){if(e.key==='Escape')close.click()}document.addEventListener('keydown',onKey);close.focus();
}

function drawSide(x,title,c,role,img,left,top){let color=role==='attacker'?'#e53935':'#1976d2';x.strokeStyle='#ddd';x.strokeRect(left,top,645,755);x.textAlign='left';x.fillStyle=color;x.font='700 27px sans-serif';x.fillText(title,left+28,top+45);drawImageCover(x,img,left+30,top+70,132);x.fillStyle='#222';x.font='700 25px sans-serif';wrapCanvasText(x,c?.name||'未選択',left+185,top+120,420,30,2);x.font='20px sans-serif';let baseRows=role==='attacker'?[`Power: ${$('attackerPower').value}`,`属性: ${lastResult.s.a}`,`イベント補正: ${$('attackerEvent').selectedOptions[0].text}`,`解答速度: ${$('answerSpeed').selectedOptions[0].text}`,`自力モード: ${$('selfMode').selectedOptions[0].text}`,`問題レベル: ${$('questionLevel').selectedOptions[0].text}`]:[`HP: ${$('defenderHp').value}`,`属性: ${lastResult.s.d}`,`イベント補正: ${$('defenderEvent').selectedOptions[0].text}`,`耐久値: ${lastResult.durability.toLocaleString()}`],extraRows=[];if(role==='attacker'&&lastResult.detailMode)extraRows.push(`生存補正: ${$('survivalTurns').selectedOptions[0].text}`);vals(role==='attacker'?'attackBuffRate':'cutRate').forEach((v,i)=>extraRows.push(`${role==='attacker'?'追加攻撃力':'追加軽減率'}${i+1}: ${fmt(v)}%`));if(lastResult.detailMode&&role==='attacker'){extraRows.push(`全体攻撃: ${($('allAttack').value==='1'||lastResult.s.all===true)?'あり（×5）':'なし'}`);vals('extraHit').forEach((v,i)=>extraRows.push(`追加連撃効果${i+1}: ${fmt(v)}回`))}else if(lastResult.detailMode&&role==='defender'){vals('extraHeal').forEach((v,i)=>extraRows.push(`追加回復効果${i+1}: ${fmt(v)}%`))}let y=top+245;for(let r of baseRows){x.fillText(r,left+28,y);y+=30}let ownDescription=skillEnabled[role]?(c?.details?.skill||'スキルなし'):null,ownEffects=ownAppliedLabels(role,lastResult.s),borrowed=borrowedAppliedLabels(role,lastResult.s);if(ownDescription||borrowed.length){y+=5;x.fillStyle='#f5f7fa';x.fillRect(left+20,y-22,605,Math.min(168,50+(ownDescription?50:0)+(borrowed.length?50:0)));x.fillStyle='#222';x.font='700 19px sans-serif';x.fillText('スキル適用',left+30,y);y+=28;x.font='17px sans-serif';if(ownDescription){y=wrapCanvasText(x,'自キャラ: '+ownDescription,left+30,y,575,23,3);if(ownEffects.length)y=wrapCanvasText(x,'効果量: '+ownEffects.join('・'),left+30,y,575,23,2)}if(borrowed.length)y=wrapCanvasText(x,'他キャラ: '+borrowed.join('・'),left+30,y,575,23,3);y+=8}x.font='20px sans-serif';for(let r of extraRows){x.fillText(r,left+28,y);y+=30}if(role==='defender'&&lastResult.detailMode&&ghostData){y+=10;x.font='700 19px sans-serif';x.fillText('幽霊攻撃への耐久',left+28,y);x.font='18px sans-serif';x.fillText(ghostData.survive,left+28,y+28);x.fillText(ghostData.kill,left+28,y+56)}}


/* 通常ダメージ計算機の任意保存履歴。協力計算の履歴とは独立。 */
const CALCULATOR_HISTORY_KEY='eigoCalculatorHistoryV1';
const CALCULATOR_HISTORY_FIELDS=['attackerPower','attackerAttribute','attackerEvent','answerSpeed','selfMode','questionLevel','survivalTurns','allAttack','defenderHp','defenderAttribute','defenderEvent',...Array.from({length:4},(_,i)=>'attackBuffRate'+(i+1)),...Array.from({length:3},(_,i)=>'extraHit'+(i+1)),...Array.from({length:6},(_,i)=>'cutRate'+(i+1)),...Array.from({length:3},(_,i)=>'extraHeal'+(i+1))];
function calculatorHistoryRead(){try{const a=JSON.parse(localStorage.getItem(CALCULATOR_HISTORY_KEY)||'[]');return Array.isArray(a)?a.filter(x=>x&&x.id&&x.fields).slice(0,100):[]}catch{return []}}
function calculatorHistoryWrite(items){try{localStorage.setItem(CALCULATOR_HISTORY_KEY,JSON.stringify(items));return true}catch{alert('計算履歴を保存できませんでした。ブラウザーの保存容量を確認してください。');return false}}
function calculatorHistorySnapshot(){return {id:String(Date.now())+'-'+Math.random().toString(36).slice(2),savedAt:new Date().toISOString(),fields:Object.fromEntries(CALCULATOR_HISTORY_FIELDS.map(id=>[id,$(id)?.value??''])),characters:{attacker:selected.attacker,defender:selected.defender},skillEnabled:{...skillEnabled},borrowedSkills:{attacker:[...borrowedSkills.attacker],defender:[...borrowedSkills.defender]},borrowedEnabled:{attacker:[...borrowedEnabled.attacker],defender:[...borrowedEnabled.defender]},detailMode,result:{status:lastResult?.st||'',min:lastResult?.mn??0,max:lastResult?.mx??0,range:$('damageRange')?.textContent||''}}}
function calculatorHistorySave(){calculate();let items=calculatorHistoryRead();items.unshift(calculatorHistorySnapshot());items=items.slice(0,100);if(calculatorHistoryWrite(items))calculatorHistoryRender()}
function calculatorHistoryRestore(id){const item=calculatorHistoryRead().find(x=>x.id===id);if(!item)return;for(const role of ['attacker','defender']){const c=item.characters?.[role];if(c)setCharacter(role,c,true);else removeCharacter(role)}for(const [key,value] of Object.entries(item.fields||{})){const el=$(key);if(el)el.value=value}for(const role of ['attacker','defender']){skillEnabled[role]=!!item.skillEnabled?.[role];borrowedSkills[role]=Array.isArray(item.borrowedSkills?.[role])?[...item.borrowedSkills[role]]:[];borrowedEnabled[role]=borrowedSkills[role].map((_,i)=>!!item.borrowedEnabled?.[role]?.[i]);syncSkill(role);renderBorrowedSkills(role)}detailMode=!!item.detailMode;syncDetailMode();for(const [prefix,count] of [['attackBuffRate',4],['extraHit',3],['cutRate',6],['extraHeal',3]])progress(prefix,count);calculate()}
function calculatorHistoryDelete(id){const items=calculatorHistoryRead().filter(x=>x.id!==id);if(calculatorHistoryWrite(items))calculatorHistoryRender()}
function calculatorHistoryRender(){const list=$('calculatorHistoryList'),count=$('calculatorHistoryCount');if(!list||!count)return;const items=calculatorHistoryRead();count.textContent=items.length+'件';list.replaceChildren();if(!items.length){const empty=document.createElement('p');empty.className='calculator-history-empty';empty.textContent='保存した計算結果はありません。';list.append(empty);return}for(const item of items){const card=document.createElement('div');card.className='calculator-history-item';const main=document.createElement('div');main.className='calculator-history-main';const names=document.createElement('strong');names.textContent=(item.characters?.attacker?.name||'攻撃キャラ未選択')+' → '+(item.characters?.defender?.name||'対象未選択');const date=document.createElement('time');const d=new Date(item.savedAt);date.textContent=Number.isNaN(d.getTime())?'保存日時不明':d.toLocaleString('ja-JP');main.append(names,date);const result=document.createElement('div');result.className='calculator-history-result';result.textContent=(item.result?.status||'')+'　'+(item.result?.range||'');const actions=document.createElement('div');actions.className='calculator-history-actions';const apply=document.createElement('button');apply.type='button';apply.textContent='計算機に反映';apply.onclick=()=>calculatorHistoryRestore(item.id);const del=document.createElement('button');del.type='button';del.className='calculator-history-delete';del.textContent='削除';del.onclick=()=>calculatorHistoryDelete(item.id);actions.append(apply,del);card.append(main,result,actions);list.append(card)}}
function calculatorHistoryInit(){const button=$('saveCalculation');if(!button||button.dataset.historyBound)return;button.dataset.historyBound='1';button.addEventListener('click',calculatorHistorySave);calculatorHistoryRender()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',calculatorHistoryInit);else calculatorHistoryInit();
