/* 英語物語 対戦ツール: calculator */
function resetProgressive(prefix,count){for(let i=1;i<=count;i++){let q=$(prefix+i);if(q)q.value=''}progress(prefix,count)}
function resetExceptCharacter(r){skillEnabled[r]=false;syncSkill(r);if(r==='attacker'){$('answerSpeed').value='1.2';$('selfMode').value='1.2';$('questionLevel').value='1.8';$('survivalTurns').value='0';$('allAttack').value='0';resetProgressive('attackBuffRate',4);resetProgressive('extraHit',3)}else{resetProgressive('cutRate',6);resetProgressive('extraHeal',3)}calculate()}
function removeCharacter(r){selected[r]=null;skillEnabled[r]=false;let p=$(r+'Picker');p.querySelector('.portrait').style.backgroundImage='';p.querySelector('strong').textContent='未選択';p.querySelector('small').textContent='タップして図鑑から選択';$(r==='attacker'?'attackerPower':'defenderHp').value=0;$(r+'Attribute').value='火';$(r+'Event').value='1';$(r+'Skill').textContent='キャラ未選択';$(r+'SkillBtn').disabled=true;syncSkill(r);calculate()}
function resetAll(){removeCharacter('attacker');removeCharacter('defender');resetExceptCharacter('attacker');resetExceptCharacter('defender');$('mode').selectedIndex=0;$('attribute').selectedIndex=0;$('cost').selectedIndex=0;$('waku').selectedIndex=0;$('hosei').value='0';$('minCount').value='10';$('tierResult').innerHTML='';calculate()}
function swap(){let a=selected.attacker,d=selected.defender,as=skillEnabled.attacker,ds=skillEnabled.defender;if(d){skillEnabled.attacker=ds;setCharacter('attacker',d,true)}if(a){skillEnabled.defender=as;setCharacter('defender',a,true)}}
function toggleSkill(r){skillEnabled[r]=!skillEnabled[r];syncSkill(r);calculate()}
function syncSkill(r){let b=$(r+'SkillBtn');b.textContent=skillEnabled[r]?'スキル解除':'スキル使用';b.classList.toggle('active',skillEnabled[r])}
function raw(v){let n=parseFloat(String(v??'').replace('%',''));return Number.isFinite(n)?n:NaN}
function en(e){let n=String(e?.effect??e?.['スキル効果']??'').trim();if(['被ダメージ減少','ダメージカット','シールド'].includes(n))return'シールド';if(['攻撃集中','集中'].includes(n))return'集中';if(['攻撃力アップ','攻撃力増加','攻撃力上昇'].includes(n))return'攻撃力アップ';if(['属性変更','属性変化','色変'].includes(n))return'色変';if(['連続攻撃','連撃'].includes(n))return'連撃';return n}
function amt(e){let n=raw(e?.value??e?.amount??e?.['効果量']);return ['シールド','集中','攻撃力アップ','回復'].includes(en(e))&&Number.isFinite(n)&&Math.abs(n)<=10?n*100:n}
function effects(r){let a=selected[r]?.details?.skillEffects;return skillEnabled[r]&&Array.isArray(a)?a:[]}
function conditionAttribute(value){let s=canon(value);if(!s||['自身','全員','味方全員','リーダー','敵全員','すべて'].includes(s))return null;return ATTRS.filter(a=>a!=='全').sort((a,b)=>b.length-a.length).find(a=>s.includes(a))||null}
function matches(cur,req){req=conditionAttribute(req);if(!req)return true;cur=canon(cur);if(cur==='全')return true;return ['火水','水風','風火'].includes(req)?cur===req:cur.includes(req)}
function applies(e,own,opponent){let applier=e?.applier??e?.['適用者'],target=e?.target??e?.['対象者'],targetAttribute=e?.targetAttribute,opponentTarget=/敵|攻撃/.test(String(target??'')),recipient=opponentTarget?opponent:own;return matches(own,applier)&&matches(recipient,targetAttribute??target)}
function colorValue(e){let v=canon(e?.value??e?.amount??e?.['効果量']);return ATTRS.includes(v)?v:null}
function skillState(a,d,h){let o={a,d,atk:1,hits:1,cuts:[],healRates:[],all:false,concentration:false,al:[],dl:[]};for(let r of ['attacker','defender'])for(let e of effects(r)){if(en(e)!=='色変')continue;let own=r==='attacker'?o.a:o.d,opp=r==='attacker'?o.d:o.a;if(!applies(e,own,opp))continue;let v=colorValue(e);if(v)r==='attacker'?o.a=v:o.d=v}for(let r of ['attacker','defender']){let own=r==='attacker'?o.a:o.d,opp=r==='attacker'?o.d:o.a,lab=r==='attacker'?o.al:o.dl;for(let e of effects(r)){let n=en(e);if(!n)continue;if(!applies(e,own,opp)){lab.push(n+'：条件不成立');continue}if(n==='色変'){let v=colorValue(e);lab.push(v?`属性を${v}に変更`:'属性変更：データ確認必要');continue}if(['遅延','短縮','蘇生'].includes(n)){lab.push(n+'：計算対象外');continue}let v=amt(e);if(n==='攻撃力アップ'&&r==='attacker'&&Number.isFinite(v)){o.atk*=1+v/100;lab.push(`攻撃力+${fmt(v)}%`)}else if(n==='連撃'&&r==='attacker'){let q=Math.max(1,Math.floor(raw(e.value??e.amount)));o.hits+=q-1;lab.push(`${q}回連撃`)}else if(n==='全体攻撃'&&r==='attacker'){o.all=true;lab.push('全体攻撃×5')}else if(['シールド','集中'].includes(n)&&r==='defender'&&Number.isFinite(v)){o.cuts.push(v);if(n==='集中')o.concentration=true;lab.push(`${fmt(v)}%軽減`)}else if(n==='回復'&&r==='defender'&&Number.isFinite(v)){o.healRates.push(v);lab.push(`回復${fmt(v)}%`)}else if(!['攻撃力アップ','連撃','全体攻撃','シールド','集中','回復'].includes(n)){lab.push(n+'：計算対象外')}}}return o}
function vals(p){return Array.from({length:fieldCount(p)},(_,i)=>raw($(p+(i+1))?.value)).filter(Number.isFinite)}
function amul(){return vals('attackBuffRate').reduce((m,v)=>m*(1+v/100),1)}
function cmul(a){return a.map(v=>Math.max(0,Math.min(100,v))).sort((x,y)=>y-x).reduce((m,v,i)=>m*(1-v/100*3/(2*(i+1)+1)),1)}
function manualHits(){return vals('extraHit').reduce((sum,v)=>sum+Math.max(0,Math.floor(v)-1),0)}
function effectiveHeal(h,maxHp,rates){let current=h,total=0,cap=Math.max(0,Number(maxHp)||0);for(let rate of rates){let raw=Math.floor(h*rate/100),full=Math.min(raw,Math.max(0,cap-current)),half=raw-full,added=full+Math.floor(half/2);current+=added;total+=added}return total}
function durabilityValue(h,cuts){let damageRate=cmul(cuts);return h>0&&damageRate>0?Math.floor(h/damageRate):0}
function calculate(){
  let p=Math.max(0,+$('attackerPower').value||0),hp=Math.max(0,+$('defenderHp').value||0)*($('defenderEvent').value||1),s=skillState($('attackerAttribute').value,$('defenderAttribute').value,hp),maxHp=Number(selected.defender?.details?.limitHp??$('defenderHp').value)||0,heal=effectiveHeal(hp,maxHp,s.healRates.concat(vals('extraHeal'))),eh=hp+heal,rt=MATCH[s.a]?.[s.d]??1,sur=1.3**(+$('survivalTurns').value||0),hits=s.hits+manualHits(),manualCuts=vals('cutRate'),allRequested=$('allAttack').value==='1'||s.all===true,allApplied=allRequested&&(s.concentration||manualCuts.length>0),all=allApplied?5:1,base=p*(+$('answerSpeed').value||1)*(+$('selfMode').value||1)*(+$('attackerEvent').value||1)*(+$('questionLevel').value||1)*sur*amul()*s.atk*.75*cmul(manualCuts.concat(s.cuts))*all,perHit=base*rt,b=perHit*hits,mn=Math.floor(b*.9),mx=Math.floor(b*1.1),mp=eh?Math.floor(mn/eh*100):0,xp=eh?Math.floor(mx/eh*100):0,st=!p||!eh?'数値を入力してください':mn>=eh?'確定撃破':mx>=eh?'乱数撃破':'撃破不可';
  let remainMin=Math.max(0,eh-mx),remainMax=Math.max(0,eh-mn),durability=durabilityValue(eh,manualCuts.concat(s.cuts));$('attackerEffect').textContent=s.al.join('・');$('defenderEffect').textContent=s.dl.join('・');$('killResult').textContent=st;$('damageRange').textContent=`${mn.toLocaleString()}～${mx.toLocaleString()}（${mp}%～${xp}%）`;$('remainingHp').textContent=st==='撃破不可'?`残りHP ${remainMin.toLocaleString()}～${remainMax.toLocaleString()}`:'';$('durabilityValue').textContent=durability.toLocaleString();
  let hitInfo='';
  if(hits>1&&eh&&mx>=eh){let minPerHit=Math.floor(perHit*.9),maxPerHit=Math.floor(perHit*1.1),first=Math.min(hits,Math.ceil(eh/maxPerHit)),last=Math.min(hits,Math.ceil(eh/minPerHit)),kill=first===last?`${first}発で撃破`:`${first}～${last}発で撃破`,spareMin=Math.max(0,hits-last),spareMax=Math.max(0,hits-first),spareHits=spareMin===spareMax?`${spareMin}発`:`${spareMin}～${spareMax}発`,sparePerHit=base*(MATCH[s.a]?.['全']??2/3),spareDamageMin=Math.floor(sparePerHit*.9*spareMin),spareDamageMax=Math.floor(sparePerHit*1.1*spareMax),spareLabel=allApplied&&spareMax>0?`余剰火力（属性相性 2/3）: ${spareHits}（${spareDamageMin.toLocaleString()}～${spareDamageMax.toLocaleString()}）×全体`:`余剰火力（属性相性 2/3）: ${spareHits}（${spareDamageMin.toLocaleString()}～${spareDamageMax.toLocaleString()}）`;hitInfo=`${kill}<br><small>${spareLabel}</small>`}
  $('multiHitResult').innerHTML=hitInfo;$('allAttackWarning').textContent=allRequested&&!allApplied?'全体スキルが使用されています。引き継いだ庇うスキルの効果量を追加軽減率として入力し忘れていませんか？':'';lastResult={st,mn,mx,mp,xp,eh,s,allApplied,remainMin,remainMax,durability};renderGhost(eh)
}
function renderGhost(h){if(!h){$('ghostResult').textContent='攻撃対象のHPを入力してください';ghostData=null;return}let b=1296,mn=Math.floor(b*.9),mx=Math.floor(b*1.1),first=Math.ceil(h/mx),last=Math.ceil(h/mn);ghostData={survive:`${Math.max(0,first-1)}～${Math.max(0,last-1)}発耐え`,kill:`${first}～${last}発目で撃破される`};$('ghostResult').innerHTML=`<div><b>${ghostData.survive}</b></div><div><b>${ghostData.kill}</b></div>`}
function pickerImageUrl(role){let bg=$(role+'Picker').querySelector('.portrait').style.backgroundImage;return bg&&bg!=='none'?bg.slice(5,-2):''}
function portraitElement(role){return $(role+'Picker').querySelector('.portrait')}
function imageUrlCandidates(url){let a=[url];try{let u=new URL(url),m;if(u.hostname==='drive.google.com'&&(m=u.pathname.match(/\/file\/d\/([^/]+)/)))a.unshift('https://lh3.googleusercontent.com/d/'+m[1]);if(u.hostname==='github.com'&&u.pathname.includes('/blob/'))a.unshift(url.replace('https://github.com/','https://raw.githubusercontent.com/').replace('/blob/','/'));if(u.hostname.endsWith('githubusercontent.com'))a.unshift(url)}catch{}return[...new Set(a.filter(Boolean))]}
async function loadImg(url){for(let candidate of imageUrlCandidates(url)){try{let res=await fetch(candidate,{mode:'cors',cache:'force-cache',credentials:'omit'});if(!res.ok)continue;let blob=await res.blob(),objectUrl=URL.createObjectURL(blob),im=await new Promise((resolve,reject)=>{let x=new Image;x.onload=()=>resolve(x);x.onerror=reject;x.src=objectUrl});URL.revokeObjectURL(objectUrl);return im}catch{}try{let im=await new Promise((resolve,reject)=>{let x=new Image;x.crossOrigin='anonymous';x.referrerPolicy='no-referrer';x.onload=()=>resolve(x);x.onerror=reject;x.src=candidate});return im}catch{}}return null}
function wrapCanvasText(x,text,left,y,maxWidth,lineHeight,maxLines=3){let line='',lines=[];for(let ch of String(text||'')){if(x.measureText(line+ch).width>maxWidth&&line){lines.push(line);line=ch;if(lines.length===maxLines-1)break}else line+=ch}if(line&&lines.length<maxLines)lines.push(line);for(let s of lines){x.fillText(s,left,y);y+=lineHeight}return y}
function drawImageCover(x,img,left,top,size){x.save();x.fillStyle='#f1f3f5';x.fillRect(left,top,size,size);if(img){let scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;x.drawImage(img,left+(size-w)/2,top+(size-h)/2,w,h)}else{x.fillStyle='#6b7280';x.font='16px sans-serif';x.textAlign='center';x.fillText('画像読込不可',left+size/2,top+size/2+6)}x.restore()}
async function createResultImage(){if(!lastResult)return null;let[ai,di]=await Promise.all([loadImg(selected.attacker?.imageUrl||pickerImageUrl('attacker')),loadImg(selected.defender?.imageUrl||pickerImageUrl('defender'))]);let scale=2,c=document.createElement('canvas'),x=c.getContext('2d');c.width=1400*scale;c.height=1160*scale;x.scale(scale,scale);x.fillStyle='#fff';x.fillRect(0,0,1400,1160);x.textBaseline='alphabetic';x.fillStyle='#222';x.textAlign='center';x.font='700 34px sans-serif';x.fillText('ダメージ計算結果',700,54);drawSide(x,'攻撃キャラ',selected.attacker,'attacker',ai,45,85);drawSide(x,'攻撃対象キャラ',selected.defender,'defender',di,710,85);x.strokeStyle='#ddd';x.strokeRect(45,875,1310,240);x.fillStyle='#e53935';x.font='700 34px sans-serif';x.fillText(lastResult.st,700,925);x.fillStyle='#222';x.font='700 27px sans-serif';x.fillText(`${lastResult.mn.toLocaleString()}～${lastResult.mx.toLocaleString()}（${lastResult.mp}%～${lastResult.xp}%）`,700,970);let resultY=1008;if(lastResult.st==='撃破不可'){x.font='700 22px sans-serif';x.fillText(`残りHP ${lastResult.remainMin.toLocaleString()}～${lastResult.remainMax.toLocaleString()}`,700,resultY);resultY+=38}x.font='700 21px sans-serif';x.fillText(`耐久値（属性相性2/3）: ${lastResult.durability.toLocaleString()}`,700,resultY);try{return c.toDataURL('image/png',1)}catch{return null}}
async function downloadResult(){let b=$('downloadResult'),old=b.textContent;b.disabled=true;b.textContent='画像を作成中…';let data=null;try{data=await createResultImage()}catch{}b.disabled=false;b.textContent=old;if(!data){alert('保存画像を作成できませんでした。');return}let overlay=$('resultPreview');if(!overlay){overlay=document.createElement('div');overlay.id='resultPreview';overlay.className='overlay';overlay.innerHTML='<div class="modal preview-modal"><button class="close close-button" data-preview-close>×</button><h2>保存画像のプレビュー</h2><img id="resultPreviewImage"><div class="preview-actions"><button id="saveResultImage" class="primary">画像をダウンロード</button><button data-preview-close>閉じる</button></div></div>';document.body.append(overlay)}$('resultPreviewImage').src=data;overlay.hidden=false;overlay.querySelectorAll('[data-preview-close]').forEach(q=>q.onclick=()=>overlay.hidden=true);$('saveResultImage').onclick=()=>{let a=document.createElement('a');a.download='damage-result.png';a.href=data;a.click()}}
function drawSide(x,title,c,role,img,left,top){let color=role==='attacker'?'#e53935':'#1976d2';x.strokeStyle='#ddd';x.strokeRect(left,top,645,755);x.textAlign='left';x.fillStyle=color;x.font='700 27px sans-serif';x.fillText(title,left+28,top+45);drawImageCover(x,img,left+30,top+70,132);x.fillStyle='#222';x.font='700 25px sans-serif';wrapCanvasText(x,c?.name||'未選択',left+185,top+120,420,30,2);x.font='20px sans-serif';let rows=role==='attacker'?[`Power: ${$('attackerPower').value}`,`属性: ${lastResult.s.a}`,`イベント補正: ${$('attackerEvent').selectedOptions[0].text}`,`解答速度: ${$('answerSpeed').selectedOptions[0].text}`,`自力モード: ${$('selfMode').selectedOptions[0].text}`,`問題レベル: ${$('questionLevel').selectedOptions[0].text}`,`生存補正: ${$('survivalTurns').selectedOptions[0].text}`]:[`HP: ${$('defenderHp').value}`,`属性: ${lastResult.s.d}`,`イベント補正: ${$('defenderEvent').selectedOptions[0].text}`];vals(role==='attacker'?'attackBuffRate':'cutRate').forEach((v,i)=>rows.push(`${role==='attacker'?'追加攻撃力':'追加軽減率'}${i+1}: ${fmt(v)}%`));if(role==='attacker'){rows.push(`全体攻撃: ${($('allAttack').value==='1'||lastResult.s.all===true)?'あり（×5）':'なし'}`);vals('extraHit').forEach((v,i)=>rows.push(`追加連撃効果${i+1}: ${fmt(v)}回`))}else{vals('extraHeal').forEach((v,i)=>rows.push(`追加回復効果${i+1}: ${fmt(v)}%`))}let y=top+245;for(let r of rows){x.fillText(r,left+28,y);y+=30}if(skillEnabled[role]){y+=8;x.font='18px sans-serif';y=wrapCanvasText(x,'スキル: '+(c?.details?.skill||''),left+28,y,590,25,4);y=wrapCanvasText(x,'反映: '+$(role+'Effect').textContent,left+28,y,590,25,3)}if(role==='defender'&&ghostData){y+=10;x.font='700 19px sans-serif';x.fillText('幽霊攻撃への耐久',left+28,y);x.font='18px sans-serif';x.fillText(ghostData.survive,left+28,y+28);x.fillText(ghostData.kill,left+28,y+56);if(ghostData.rate)x.fillText(ghostData.rate,left+28,y+84)}}
