/* 英語物語 対戦ツール: catalog */
function renderTree(items,box,opened){let t={};items.forEach(x=>{let c=x.c,a=c.largeCategory||'未分類',b=c.middleCategory||'その他',s=c.smallCategory||'その他',h=c.heading||'';((((t[a]??={})[b]??={})[s]??={})[h]??=[]).push(x)});box.innerHTML='';Object.entries(t).forEach(([a,m])=>{let A=folder(a,'zk-b1 '+(a==='特殊ゆる'?'special':'normal'),opened),ab=A.lastChild;Object.entries(m).forEach(([b,sm])=>{let B=folder(b,'zk-b2',opened),bb=B.lastChild;Object.entries(sm).forEach(([s,hm])=>{if(b==='伝'){let z=document.createElement('div');z.className='zk-head';z.textContent=s;bb.append(z);Object.entries(hm).forEach(([h,list])=>{if(h&&h!=='その他'){let q=document.createElement('div');q.className='zk-head';q.textContent=h;bb.append(q)}let g=document.createElement('div');g.className='zk-grid';list.forEach(x=>g.append(card(x.c,x.i,opened)));bb.append(g)});return}let S=s==='その他'?null:folder(s,'zk-b3',opened),sb=S?S.lastChild:bb;Object.entries(hm).forEach(([h,list])=>{if(h&&h!=='その他'){let z=document.createElement('div');z.className='zk-head';z.textContent=h;sb.append(z)}let g=document.createElement('div');g.className='zk-grid';list.forEach(x=>g.append(card(x.c,x.i,opened)));sb.append(g)});if(S)bb.append(S)});ab.append(B)});box.append(A)})}
function folder(name,cls,o){let w=document.createElement('div'),b=document.createElement('button'),d=document.createElement('div'),a=document.createElement('span');w.className='zk-l1';b.className=cls;a.textContent=o?'▼':'▶';d.className='zk-body'+(o?' open':'');b.append(document.createTextNode(name),a);b.onclick=()=>{let x=d.classList.toggle('open');a.textContent=x?'▼':'▶'};w.append(b,d);return w}
function card(c,i,p){let b=document.createElement('button'),im=document.createElement('img'),sm=document.createElement('small');b.className='zk-card';b.dataset.charIndex=String(i);im.loading='lazy';im.decoding='async';im.width=64;im.height=64;im.src=c.imageUrl||'';sm.textContent=c.name||'';b.append(im,sm);b.onclick=()=>{let box=b.closest('#pickerBox,#zkBox'),order=box?[...box.querySelectorAll('.zk-card[data-char-index]')].map(x=>Number(x.dataset.charIndex)):null;openDetail(i,p,order&&order.length?order:null)};return b}
function renderZukan(){let r=results($('zkSearch').value);$('zkCount').textContent=`${r.length}件 / 全${chars.length}体`;renderTree(r,$('zkBox'),Boolean($('zkSearch').value))}
function openPicker(r){pickerRole=r;$('pickerTitle').textContent=(r==='attacker'?'攻撃キャラ':'攻撃対象キャラ')+'を選択';$('pickerSearch').value='';renderPicker();$('picker').hidden=false}
function renderPicker(){renderTree(results($('pickerSearch').value),$('pickerBox'),Boolean($('pickerSearch').value))}
function theme(attr){const colors={火:['#e53935','#ffe7e5'],水:['#1976d2','#e3f0ff'],風:['#7cbf19','#edf8d8']},parts=['火','水','風'].filter(x=>canon(attr).includes(x));if(!parts.length)return['#6c757d','#6c757d','#f1f3f5'];const accent=colors[parts[0]][0],bar=parts.length>1?'linear-gradient(135deg,'+parts.map(x=>colors[x][0]).join(',')+')':accent,soft=parts.length>1?'linear-gradient(135deg,'+parts.map(x=>colors[x][1]).join(',')+')':colors[parts[0]][1];return[accent,bar,soft]}
function openDetail(i,p=false,o=null){let c=chars[i],d=c?.details||{};if(!c)return;current=i;fromPicker=p;detailOrder=o||results(p?$('pickerSearch').value:$('zkSearch').value).map(x=>x.i);let [accent,bar,soft]=theme(d.attribute),panel=$('detail').querySelector('.detail-modal');panel.style.setProperty('--accent',accent);panel.style.setProperty('--bar',bar);panel.style.setProperty('--soft',soft);$('detailImage').src=c.imageUrl||'';$('detailName').textContent=c.name||'';$('detailMeta').textContent=[d.rare,canon(d.attribute),d.cost!=null?'Cost '+d.cost:null].filter(Boolean).join(' / ');$('detailStats').innerHTML=[['無凸HP',d.hp],['無凸Power',d.power],['完凸HP',d.limitHp],['完凸Power',d.limitPower]].filter(x=>x[1]!=null).map(x=>`<div><span>${x[0]}</span><b>${Number(x[1]).toLocaleString()}</b></div>`).join('');$('detailSkill').textContent=d.skill||'';$('detailTurn').textContent=d.skillTurn!=null?'必要ターン '+d.skillTurn:'';document.querySelector('[data-role="attacker"]').hidden=p;document.querySelector('[data-role="defender"]').hidden=p;document.querySelector('[data-role="picker"]').hidden=!p;$('detail').hidden=false}
function move(d){lastDirection=d<0?-1:1;let p=detailOrder.indexOf(current);if(p>=0&&detailOrder.length)openDetail(detailOrder[(p+lastDirection+detailOrder.length)%detailOrder.length],fromPicker,detailOrder)}
function choose(r){if(r==='picker')r=pickerRole;setCharacter(r,chars[current]);$('detail').hidden=$('picker').hidden=true;showPage('calculator')}
function norm(x){let s=canon(x);return ATTRS.filter(a=>a!=='全').sort((a,b)=>b.length-a.length).find(a=>s.includes(a))||'全'}
function setCharacter(r,c,keep=false){selected[r]=c;if(!keep)skillEnabled[r]=false;let d=c.details||{},p=$(r+'Picker');p.querySelector('.portrait').style.backgroundImage=`url("${String(c.imageUrl||'').replace(/"/g,'')}")`;p.querySelector('strong').textContent=c.name||'';p.querySelector('small').textContent=[d.rare,canon(d.attribute),d.cost!=null?'Cost '+d.cost:null].filter(Boolean).join(' / ');$(r==='attacker'?'attackerPower':'defenderHp').value=Number(r==='attacker'?(d.limitPower??d.power??0):(d.limitHp??d.hp??0));$(r+'Attribute').value=norm(d.attribute);$(r+'Event').value='1';if(r==='attacker'&&!keep)$('survivalTurns').value='0';$(r+'Skill').textContent=d.skill||'スキルなし';$(r+'SkillBtn').disabled=!d.skill;syncSkill(r);calculate()}
