/* 英語物語 対戦ツール: cooperative damage calculator build 20260915-101 */
const COOP_LAYER_MULTIPLIERS=[2.5,2.5,8,10,50],COOP_DAMAGE_BASE=2.1492,COOP_SLOTS=5,COOP_MAX_ROWS=5,COOP_STORAGE_KEY='eigoCoopCalculatorV1';
let coopEnemies=Array.from({length:15},()=>({character:null,hp:0,attribute:'火'})),coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(COOP_SLOTS).fill(null)),coopVisibleRows=1,coopClipboard=null,coopPickerTarget=null,coopDetailMode=false,coopStoredState=null;
addEventListener('DOMContentLoaded',initCoop);
function initCoop(){if(!$('coopEnemies'))return;loadCoopState();renderCoopEnemies();renderCoopDecks();$('coopRecommend').onclick=recommendCoopDecks;$('coopReset').onclick=resetCoop;$('coopDeckReset').onclick=resetCoopDecks;$('coopDetailMode').onclick=()=>{coopDetailMode=!coopDetailMode;syncCoopDetailMode();renderCoopEnemies();saveCoopState()};syncCoopDetailMode();calculateCoop()}
function coopCharacterKey(c){return String(c?.id??c?.details?.id??c?.name??'')}
function coopFindCharacter(key){return chars.find(c=>coopCharacterKey(c)===String(key))||null}
function loadCoopState(){try{coopStoredState=JSON.parse(localStorage.getItem(COOP_STORAGE_KEY)||'null');if(!coopStoredState)return;coopDetailMode=!!coopStoredState.detailMode;coopVisibleRows=Math.max(1,Math.min(COOP_MAX_ROWS,Number(coopStoredState.visibleRows)||1));(coopStoredState.enemies||[]).slice(0,15).forEach((e,i)=>{coopEnemies[i].hp=Math.max(0,Number(e.hp)||0);coopEnemies[i].attribute=ATTRS.includes(e.attribute)?e.attribute:'火'})}catch{coopStoredState=null}}
function hydrateCoopState(){if(!chars.length)return;if(coopStoredState){(coopStoredState.enemies||[]).slice(0,15).forEach((e,i)=>coopEnemies[i].character=coopFindCharacter(e.key));(coopStoredState.decks||[]).slice(0,5).forEach((row,r)=>(row||[]).slice(0,5).forEach((key,s)=>coopDecks[r][s]=coopFindCharacter(key)))}renderCoopEnemies();renderCoopDecks()}
function saveCoopState(){let state={detailMode:coopDetailMode,visibleRows:coopVisibleRows,enemies:coopEnemies.map(e=>({key:coopCharacterKey(e.character),hp:e.hp,attribute:e.attribute})),decks:coopDecks.map(row=>row.map(coopCharacterKey))};try{localStorage.setItem(COOP_STORAGE_KEY,JSON.stringify(state));coopStoredState=state}catch{}}
function syncCoopDetailMode(){let b=$('coopDetailMode');b.textContent=coopDetailMode?'詳細モード ON':'詳細モード OFF';b.setAttribute('aria-pressed',String(coopDetailMode))}
function coopAttrOptions(value){return ATTRS.map(a=>`<option value="${a}"${a===value?' selected':''}>${a}</option>`).join('')}
function coopImage(c){return `<span class="coop-portrait"${c?.imageUrl?` style="background-image:url(&quot;${esc(c.imageUrl)}&quot;)"`:''}></span>`}
function coopScaledHp(i){return Math.floor((coopEnemies[i].hp||0)*COOP_LAYER_MULTIPLIERS[Math.floor(i/3)])}
function renderCoopEnemies(){let box=$('coopEnemies');box.innerHTML='';for(let layer=0;layer<5;layer++){let group=document.createElement('section');group.className='coop-layer';group.innerHTML=`<button class="coop-layer-toggle" type="button"><span>${layer+1}層目（HP ×${COOP_LAYER_MULTIPLIERS[layer]}）</span><span>▼</span></button><div class="coop-layer-body"></div>`;let body=group.querySelector('.coop-layer-body');for(let pos=0;pos<3;pos++){let i=layer*3+pos,e=coopEnemies[i],row=document.createElement('article');row.className='coop-enemy-card';row.innerHTML=`<button type="button" class="coop-character">${coopImage(e.character)}<strong>${esc(e.character?.name||'敵キャラを選択')}</strong><small>${pos+1}枠目</small></button><div class="coop-enemy-summary"><span>属性 <b>${esc(e.attribute)}</b></span><span>HP <b>${coopScaledHp(i).toLocaleString()}</b></span></div><div class="coop-enemy-manual"${coopDetailMode?'':' hidden'}><label>無凸HP<input type="number" min="0" step="any" value="${e.hp||0}"></label><label>属性<select>${coopAttrOptions(e.attribute)}</select></label></div>`;row.querySelector('.coop-character').onclick=()=>openCoopPicker('enemy',i);let input=row.querySelector('input'),select=row.querySelector('select');input.oninput=ev=>{e.hp=Math.max(0,+ev.target.value||0);row.querySelector('.coop-enemy-summary b:last-child').textContent=coopScaledHp(i).toLocaleString();calculateCoop();saveCoopState()};select.oninput=ev=>{e.attribute=ev.target.value;row.querySelector('.coop-enemy-summary b:first-child').textContent=e.attribute;calculateCoop();saveCoopState()};body.append(row)}group.querySelector('.coop-layer-toggle').onclick=()=>group.classList.toggle('closed');box.append(group)}}
function renderCoopDecks(){let box=$('coopDeckRows');box.innerHTML='';for(let r=0;r<coopVisibleRows;r++){let row=document.createElement('section');row.className='coop-deck-row';row.innerHTML=`<div class="coop-deck-head"><h3>デッキ${r+1}</h3><div><button class="mini-reset coop-copy" type="button">${coopClipboard===r?'コピー中':'コピー'}</button>${coopClipboard!==null&&coopClipboard!==r?'<button class="mini-reset coop-paste" type="button">ペースト</button>':''}</div></div><div class="coop-deck-slots"></div><div class="coop-row-result" id="coopRowResult${r}"></div>`;let slots=row.querySelector('.coop-deck-slots');for(let s=0;s<5;s++){let c=coopDecks[r][s],card=document.createElement('article');card.className='coop-deck-slot';card.innerHTML=`<div class="coop-slot-head"><div class="coop-slot-layer">${s+1}層担当</div><button type="button" class="mini-reset coop-skill-check">スキル確認</button></div><button type="button" class="coop-character">${coopImage(c)}<strong>${esc(c?.name||'味方キャラを選択')}</strong><small>${s+1}枠目 / 必要ターン ${c?.details?.skillTurn??'-'}</small></button><div class="coop-skill-detail" hidden></div>`;card.querySelector('.coop-character').onclick=()=>openCoopPicker('deck',r*5+s);card.querySelector('.coop-skill-check').onclick=()=>toggleCoopSkillDetail(r,s,card.querySelector('.coop-skill-detail'));slots.append(card)}row.querySelector('.coop-copy').onclick=()=>{coopClipboard=r;renderCoopDecks()};row.querySelector('.coop-paste')?.addEventListener('click',()=>{coopDecks[r]=coopDecks[coopClipboard].slice();renderCoopDecks();saveCoopState()});box.append(row)}calculateCoop()}
function openCoopPicker(type,index){coopPickerTarget={type,index};pickerPurpose='character';$('pickerTitle').textContent=type==='enemy'?'敵キャラを選択':'味方キャラを選択';$('pickerSearch').value='';ensurePickerTools();renderPicker();$('picker').hidden=false}
function autofillFirstDeckFromEnemy(enemyIndex){let layer=Math.floor(enemyIndex/3),pos=enemyIndex%3,slot=layer;if(layer>=1&&layer<=3&&pos===1)coopDecks[0][slot]=coopEnemies[enemyIndex].character;if(layer===4&&pos===0)coopDecks[0][4]=coopEnemies[enemyIndex].character}
function chooseCoopCharacter(c){let t=coopPickerTarget;if(!t)return false;if(t.type==='enemy'){let e=coopEnemies[t.index],d=c.details||{};e.character=c;e.hp=Number(d.hp||0);e.attribute=norm(d.attribute);autofillFirstDeckFromEnemy(t.index)}else{let r=Math.floor(t.index/5),s=t.index%5;coopDecks[r][s]=c;if(r===coopVisibleRows-1&&r<COOP_MAX_ROWS-1&&coopDecks[r].some(Boolean))coopVisibleRows++}coopPickerTarget=null;$('picker').hidden=true;renderCoopEnemies();renderCoopDecks();saveCoopState();return true}
function effectDuration(e){return Math.max(1,Number(e.duration??e.turns??e.continueTurn??e['継続ターン'])||1)}
function shortenValue(e){let v=raw(e?.value??e?.amount??e?.['効果量']);return Number.isFinite(v)?Math.max(0,Math.floor(v)):0}
function coopScopeIsSelf(e){return /自身|自分/.test(String(e?.applier??e?.['適用者']??''))}
function coopEffectApplies(x,attacker,enemy){let e=x.effect,attackerAttr=norm(attacker?.details?.attribute),enemyAttr=enemy.attribute;if(coopScopeIsSelf(e)&&x.owner!==attacker)return false;return matches(attackerAttr,e.applierAttribute??e.applier)&&matches(enemyAttr,e.targetAttribute??e.target)}
function coopAvailableSkills(deck,slot,enemyAttr){let active=[],shorten=0;for(let source=0;source<=slot;source++){let c=deck[source];if(!c)continue;let turn=Number(c.details?.skillTurn??0);if(!Number.isFinite(turn))turn=0;if(turn>source+shorten)continue;let effects=skillEffectsOf(c);for(let e of effects){if(en(e)!=='短縮')continue;let recipient=deck[slot]||c,scopeOk=!coopScopeIsSelf(e)||source===slot;if(scopeOk&&matches(norm(recipient.details?.attribute),e.applierAttribute??e.applier))shorten+=shortenValue(e)}for(let e of effects)if(en(e)!=='短縮'&&source+effectDuration(e)>slot)active.push({effect:e,owner:c,source})}return{active,shorten}}
function coopEffectLabel(x,attacker,enemy){let e=x.effect,n=en(e),v=amt(e),owner=x.owner?.name||'不明';if(!coopEffectApplies(x,attacker,enemy))return `${owner}: ${n}（条件不成立）`;if(n==='攻撃力アップ')return `${owner}: 攻撃力+${fmt(v)}%`;if(n==='連撃')return `${owner}: ${Math.max(1,Math.floor(raw(e.value??e.amount)))}回連撃`;if(n==='全体攻撃')return `${owner}: 全体攻撃×5`;return `${owner}: ${n}`}
function toggleCoopSkillDetail(row,slot,box){let open=box.hidden;document.querySelectorAll('.coop-skill-detail').forEach(x=>x.hidden=true);if(!open)return;let lines=[];for(let pos=0;pos<3;pos++){let enemy=coopEnemies[slot*3+pos],skill=coopAvailableSkills(coopDecks[row],slot,enemy.attribute),attacker=coopDecks[row][slot],labels=skill.active.map(x=>coopEffectLabel(x,attacker,enemy));lines.push(`<section><b>${slot+1}層 ${pos+1}枠の敵</b><small>使用可能短縮: ${skill.shorten}</small><p>${labels.length?labels.map(esc).join('<br>'):'適用中のスキルなし'}</p></section>`)}box.innerHTML=lines.join('');box.hidden=false}
function coopDamage(c,enemy,skill){if(!c||!enemy?.hp)return 0;let d=c.details||{},power=Number(d.limitPower??d.power??0),attr=norm(d.attribute),atk=1,hits=1,all=1;for(let x of skill.active){let e=x.effect;if(!coopEffectApplies(x,c,enemy))continue;let n=en(e),v=amt(e);if(n==='攻撃力アップ'&&Number.isFinite(v))atk*=1+v/100;else if(n==='連撃')hits+=Math.max(1,Math.floor(raw(e.value??e.amount)))-1;else if(n==='全体攻撃')all=5}return Math.floor(power*COOP_DAMAGE_BASE*(MATCH[attr]?.[enemy.attribute]??1)*atk*hits*all)}
function permutations(a){if(a.length<2)return[a.slice()];let out=[];a.forEach((v,i)=>permutations(a.slice(0,i).concat(a.slice(i+1))).forEach(p=>out.push([v,...p])));return out}
function layerOutcome(order,layer){let initial=[0,1,2].map(pos=>coopScaledHp(layer*3+pos)),configured=initial.some(Boolean);if(!configured)return{configured:false,all:false,some:false};let all=true,some=false;function walk(step,hps){if(step===order.length){let ok=hps.every(h=>h<=0);all=all&&ok;some=some||ok;return}let r=order[step],c=coopDecks[r][layer];for(let pos=0;pos<3;pos++){let i=layer*3+pos,e={...coopEnemies[i],hp:initial[pos]},skill=coopAvailableSkills(coopDecks[r],layer,e.attribute),damage=coopDamage(c,e,skill),next=hps.slice();next[pos]=Math.max(0,next[pos]-damage);walk(step+1,next)}}walk(0,initial);return{configured:true,all,some}}
function calculateCoop(){if(!$('coopClearResult'))return;let activeRows=Array.from({length:coopVisibleRows},(_,r)=>r).filter(r=>coopDecks[r].some(Boolean));if(!activeRows.length){$('coopClearResult').textContent='味方デッキを入力してください';$('coopDamageResult').textContent='';$('coopResultDetails').textContent='';return}let orders=permutations(activeRows),layerAll=Array(5).fill(true),layerSome=Array(5).fill(false),configured=Array(5).fill(false);for(let order of orders)for(let layer=0;layer<5;layer++){let x=layerOutcome(order,layer);if(!x.configured)continue;configured[layer]=true;layerAll[layer]=layerAll[layer]&&x.all;layerSome[layer]=layerSome[layer]||x.some}let bad=[],random=[];for(let i=0;i<5;i++)if(configured[i]){if(!layerSome[i])bad.push(i+1);else if(!layerAll[i])random.push(i+1)}let status=!configured.some(Boolean)?'敵を入力してください':bad.length?'撃破不可能':random.length?'ランダム撃破':'確定撃破';$('coopClearResult').textContent=status;$('coopDamageResult').textContent=bad.length?`${bad.join('・')}層目で撃破不可能`:random.length?`${random.join('・')}層目で結果が変動`:'すべてのデッキ順・攻撃対象で撃破可能';$('coopResultDetails').textContent=`判定対象: ${activeRows.length}デッキ / デッキ順 ${orders.length}通り / 各層の攻撃対象3通り`;activeRows.forEach(r=>{let q=$('coopRowResult'+r);if(q)q.textContent='全デッキの順番とランダムな攻撃対象を含めて総合判定'})}
function recommendCoopDecks(){let candidates=chars.filter(c=>Number(c.details?.limitPower??c.details?.power??0)>0);for(let r=0;r<COOP_MAX_ROWS;r++)for(let s=0;s<5;s++){let enemies=[0,1,2].map(pos=>coopEnemies[s*3+pos]),worst=c=>Math.min(...enemies.map(e=>Number(c.details?.limitPower??c.details?.power??0)*(MATCH[norm(c.details?.attribute)]?.[e.attribute]??1)));coopDecks[r][s]=candidates.slice().sort((a,b)=>worst(b)-worst(a))[0]||null}coopVisibleRows=5;renderCoopDecks();saveCoopState()}

function resetCoopDecks(){coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(5).fill(null));coopVisibleRows=1;coopClipboard=null;renderCoopDecks();saveCoopState()}
function resetCoop(){coopEnemies=Array.from({length:15},()=>({character:null,hp:0,attribute:'火'}));coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(5).fill(null));coopVisibleRows=1;coopClipboard=null;coopDetailMode=false;coopStoredState=null;try{localStorage.removeItem(COOP_STORAGE_KEY)}catch{}syncCoopDetailMode();renderCoopEnemies();renderCoopDecks()}
