/* Cooperative proposal worker build 20260919-306 */
let stopped=false;
self.onmessage=e=>{const m=e.data||{};if(m.type==='cancel'){stopped=true;return}if(!['start','stage'].includes(m.type))return;stopped=false;try{
self.chars=m.chars;self.coopEnemies=m.enemies;self.coopDecks=m.decks;self.coopVisibleRows=m.visibleRows;self.coopDetailMode=!!m.detailMode;self.coopProposalTargetDecks=m.targetDecks;self.coopProposalEnemySecondFixed=!!m.enemySecondFixed;self.ATTRS=m.constants.ATTRS;self.MATCH=m.constants.MATCH;self.COOP_LAYER_MULTIPLIERS=m.constants.layerMultipliers;self.COOP_DAMAGE_BASE=m.constants.damageBase;self.coopProposalDamageScale=Number(m.constants.damageScale??1);self.COOP_SLOTS=5;self.COOP_MAX_ROWS=5;self.coopProposalOrderCache=new Map();self.coopProposalManualCertainCache=new Map();
(0,eval)(m.engineSource);const characterById=new Map(self.chars.map(c=>[coopCharacterKey(c),c]));self.coopFindCharacter=key=>characterById.get(String(key))||null;postMessage({type:'ready'});
const prefixIds=m.prefixIds||[],candidateIds=m.candidateIds||[],items=[];let checked=0,passed=0,last=performance.now();
const flush=type=>{if(!items.length)return;postMessage(type==='stage'?{type:'stageItems',items:items.splice(0),passed}:{type:'confirmedItems',confirmed:items.splice(0),passed})};
if(m.type==='stage'){const total=prefixIds.length*candidateIds.length;for(let flat=m.workerIndex;flat<total&&!stopped;flat+=m.workerCount){let prefixIndex=Math.floor(flat/candidateIds.length),candidateIndex=flat%candidateIds.length,ids=prefixIds[prefixIndex].slice();ids[m.slot]=candidateIds[candidateIndex];let deck=ids.map(coopFindCharacter),item=coopProposalPrefixLayerEvaluation(deck,m.slot,m.targetDecks);if(item){items.push({ids:coopProposalDeckIds(item.deck),score:item.score,possible:item.possible,remainingAttacks:item.remainingAttacks,residualKills:item.residualKills,singleHitOverkill:item.singleHitOverkill,preferContinuation:item.preferContinuation});passed++}checked++;if(items.length>=1000)flush('stage');let now=performance.now();if(checked%250===0||now-last>=200){postMessage({type:'progress',checked,passed,confirmed:passed});last=now}}flush('stage');postMessage({type:'stageDone',checked,passed,items:[]})
}else{const tasks=candidateIds;for(let flat=m.workerIndex;flat<tasks.length&&!stopped;flat+=m.workerCount){let ids=tasks[flat],deck=ids.map(coopFindCharacter);if(coopProposalWorks(deck,m.targetDecks)){items.push({ids:ids.slice(),repeats:m.targetDecks,overkillRate:coopProposalOverkillRate(deck)});passed++}checked++;if(items.length>=1000)flush('start');let now=performance.now();if(checked%250===0||now-last>=200){postMessage({type:'progress',checked,passed,confirmed:passed});last=now}}flush('start');postMessage({type:'done',checked,passed,confirmed:[]})}
}catch(error){postMessage({type:'error',message:String(error&&error.stack||error)})}};
