/* 英語物語 対戦ツール: cooperative damage calculator build 20260915-125 */
const COOP_LAYER_MULTIPLIERS=[2.5,2.5,8,10,50],COOP_DAMAGE_BASE=1.93428,COOP_SLOTS=5,COOP_MAX_ROWS=5,COOP_STORAGE_KEY='eigoCoopCalculatorV1';
let coopEnemies=Array.from({length:15},()=>({character:null,hp:0,attribute:'火'})),coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(COOP_SLOTS).fill(null)),coopVisibleRows=1,coopClipboard=null,coopPickerTarget=null,coopDetailMode=false,coopStoredState=null;
addEventListener('DOMContentLoaded',initCoop);
function initCoop(){if(!$('coopEnemies'))return;loadCoopState();renderCoopEnemies();renderCoopDecks();$('coopReset').onclick=resetCoop;$('coopDeckReset').onclick=resetCoopDecks;$('coopPropose').onclick=proposeCoopDecks;$('coopDetailMode').onclick=()=>{coopDetailMode=!coopDetailMode;syncCoopDetailMode();renderCoopEnemies();saveCoopState()};syncCoopDetailMode();calculateCoop()}
function coopCharacterKey(c){return String(c?.id??c?.details?.id??c?.name??'')}
function coopFindCharacter(key){return chars.find(c=>coopCharacterKey(c)===String(key))||null}
function loadCoopState(){try{coopStoredState=JSON.parse(localStorage.getItem(COOP_STORAGE_KEY)||'null');if(!coopStoredState)return;coopDetailMode=!!coopStoredState.detailMode;coopVisibleRows=Math.max(1,Math.min(COOP_MAX_ROWS,Number(coopStoredState.visibleRows)||1));(coopStoredState.enemies||[]).slice(0,15).forEach((e,i)=>{coopEnemies[i].hp=Math.max(0,Number(e.hp)||0);coopEnemies[i].attribute=ATTRS.includes(e.attribute)?e.attribute:'火'})}catch{coopStoredState=null}}
function hydrateCoopState(){if(!chars.length)return;if(coopStoredState){(coopStoredState.enemies||[]).slice(0,15).forEach((e,i)=>coopEnemies[i].character=coopFindCharacter(e.key));(coopStoredState.decks||[]).slice(0,5).forEach((row,r)=>(row||[]).slice(0,5).forEach((key,s)=>coopDecks[r][s]=coopFindCharacter(key)))}syncCoopVisibleRows();renderCoopEnemies();renderCoopDecks()}
function syncCoopVisibleRows(){let last=-1;for(let r=0;r<COOP_MAX_ROWS;r++)if(coopDecks[r].some(Boolean))last=r;coopVisibleRows=Math.min(COOP_MAX_ROWS,Math.max(1,last+2))}
function saveCoopState(){let state={detailMode:coopDetailMode,visibleRows:coopVisibleRows,enemies:coopEnemies.map(e=>({key:coopCharacterKey(e.character),hp:e.hp,attribute:e.attribute})),decks:coopDecks.map(row=>row.map(coopCharacterKey))};try{localStorage.setItem(COOP_STORAGE_KEY,JSON.stringify(state));coopStoredState=state}catch{}}
function syncCoopDetailMode(){let b=$('coopDetailMode');b.textContent=coopDetailMode?'詳細モード ON':'詳細モード OFF';b.setAttribute('aria-pressed',String(coopDetailMode))}
function coopAttrOptions(value){return ATTRS.map(a=>`<option value="${a}"${a===value?' selected':''}>${a}</option>`).join('')}
function coopImage(c){return `<span class="coop-portrait"${c?.imageUrl?` style="background-image:url(&quot;${esc(c.imageUrl)}&quot;)"`:''}></span>`}
function coopEnemyExtraHpMultiplier(c){return c?.name==='ゆる神の像＆ピヨか？'?5:1}
function coopScaledHp(i){let e=coopEnemies[i];return Math.floor((e.hp||0)*COOP_LAYER_MULTIPLIERS[Math.floor(i/3)]*coopEnemyExtraHpMultiplier(e.character))}
function renderCoopEnemies(){let box=$('coopEnemies');box.innerHTML='<button id="coopEnemiesToggle" class="coop-enemies-toggle" type="button"><span>敵1～5層をまとめて開閉</span><span class="coop-enemies-arrow">▼</span></button><div id="coopEnemiesBody" class="coop-enemies-body"></div>';let allBody=$('coopEnemiesBody'),allButton=$('coopEnemiesToggle');allButton.onclick=()=>{let closed=allBody.classList.toggle('closed');allButton.querySelector('.coop-enemies-arrow').textContent=closed?'▶':'▼'};for(let layer=0;layer<5;layer++){let group=document.createElement('section');group.className='coop-layer';group.innerHTML=`<button class="coop-layer-toggle" type="button"><span>${layer+1}層目（HP ×${COOP_LAYER_MULTIPLIERS[layer]}）</span><span class="coop-layer-arrow">▼</span></button><div class="coop-layer-body"></div>`;let body=group.querySelector('.coop-layer-body');for(let pos=0;pos<3;pos++){let i=layer*3+pos,e=coopEnemies[i],row=document.createElement('article');row.className='coop-enemy-card';row.innerHTML=`<button type="button" class="coop-character">${coopImage(e.character)}<strong>${esc(e.character?.name||'敵キャラを選択')}</strong><small>${pos+1}枠目</small></button><div class="coop-enemy-summary"><span>属性 <b>${esc(e.attribute)}</b></span><span>HP <b>${coopScaledHp(i).toLocaleString()}</b></span></div><div class="coop-enemy-manual"${coopDetailMode?'':' hidden'}><label>無凸HP<input type="number" min="0" step="any" value="${e.hp||0}"></label><label>属性<select>${coopAttrOptions(e.attribute)}</select></label></div>`;row.querySelector('.coop-character').onclick=()=>openCoopPicker('enemy',i);let input=row.querySelector('input'),select=row.querySelector('select');input.oninput=ev=>{e.hp=Math.max(0,+ev.target.value||0);row.querySelector('.coop-enemy-summary b:last-child').textContent=coopScaledHp(i).toLocaleString();calculateCoop();saveCoopState()};select.oninput=ev=>{e.attribute=ev.target.value;row.querySelector('.coop-enemy-summary b:first-child').textContent=e.attribute;calculateCoop();saveCoopState()};body.append(row)}group.querySelector('.coop-layer-toggle').onclick=()=>{let closed=group.classList.toggle('closed');group.querySelector('.coop-layer-arrow').textContent=closed?'▶':'▼'};allBody.append(group)}}
function renderCoopDecks(){let box=$('coopDeckRows');box.innerHTML='';for(let r=0;r<coopVisibleRows;r++){let row=document.createElement('section');row.className='coop-deck-row';row.innerHTML=`<div class="coop-deck-head"><h3>デッキ${r+1}</h3><div class="coop-deck-actions">${r===0?'<button class="mini-reset coop-autofill" type="button">デッキ1のみ自動入力</button>':''}<button class="mini-reset coop-copy" type="button">${coopClipboard===r?'コピー中':'コピー'}</button>${coopClipboard!==null&&coopClipboard!==r?'<button class="mini-reset coop-paste" type="button">ペースト</button>':''}${r>0?'<button class="mini-reset danger coop-delete" type="button">デッキ削除</button>':''}</div></div><div class="coop-deck-slots"></div><div class="coop-row-result" id="coopRowResult${r}"></div>`;let slots=row.querySelector('.coop-deck-slots');for(let s=0;s<5;s++){let c=coopDecks[r][s],card=document.createElement('article');card.className='coop-deck-slot';card.innerHTML=`<div class="coop-slot-main"><button type="button" class="coop-character coop-character-image-only" aria-label="${esc(c?.name||'味方キャラを選択')}" title="${esc(c?.name||'味方キャラを選択')}">${coopImage(c)}</button><button type="button" class="mini-reset coop-skill-check">スキル確認</button></div><div class="coop-skill-detail" hidden></div>`;card.querySelector('.coop-character').onclick=()=>openCoopPicker('deck',r*5+s);card.querySelector('.coop-skill-check').onclick=()=>toggleCoopSkillDetail(r,s,card.querySelector('.coop-skill-detail'));slots.append(card)}row.querySelector('.coop-autofill')?.addEventListener('click',recommendCoopDecks);row.querySelector('.coop-delete')?.addEventListener('click',()=>deleteCoopDeck(r));row.querySelector('.coop-copy').onclick=()=>{coopClipboard=r;renderCoopDecks()};row.querySelector('.coop-paste')?.addEventListener('click',()=>{coopDecks[r]=coopDecks[coopClipboard].slice();syncCoopVisibleRows();renderCoopDecks();saveCoopState()});box.append(row)}calculateCoop()}
function openCoopPicker(type,index){coopPickerTarget={type,index};pickerPurpose=type==='deck'&&index%5>0?'coopDeckRestricted':'character';$('pickerTitle').textContent=type==='enemy'?'敵キャラを選択':'味方キャラを選択';$('pickerSearch').value='';ensurePickerTools();renderPicker();$('picker').hidden=false}
function autofillFirstDeckFromEnemy(enemyIndex){let layer=Math.floor(enemyIndex/3),pos=enemyIndex%3,slot=layer;if(layer>=1&&layer<=3&&pos===1)coopDecks[0][slot]=coopEnemies[enemyIndex].character;if(layer===4&&pos===0)coopDecks[0][4]=coopEnemies[enemyIndex].character}
function chooseCoopCharacter(c){let t=coopPickerTarget;if(!t)return false;if(t.type==='enemy'){let e=coopEnemies[t.index],d=c.details||{};e.character=c;e.hp=Number(d.hp||0);e.attribute=norm(d.attribute)}else{let r=Math.floor(t.index/5),s=t.index%5;coopDecks[r][s]=c;syncCoopVisibleRows()}coopPickerTarget=null;$('picker').hidden=true;renderCoopEnemies();renderCoopDecks();saveCoopState();return true}
function effectDuration(e){let n=Number(e?.duration);return Number.isFinite(n)&&n>0?Math.floor(n):1}
function shortenValue(e){let v=raw(e?.value??e?.amount??e?.['効果量']);return Number.isFinite(v)?Math.max(0,Math.floor(v)):0}
function coopStructuredEffectValid(e){return !!e&&e.needsReview!==true&&typeof e.effect==='string'&&e.effect.length>0}
function coopScopeIsSelf(e){return /自身|自分/.test(String(e?.applier??''))}
function coopScopeIsLeader(e){return /リーダー/.test(String(e?.applier??''))}
function coopAllyMatchesEffect(e,owner,recipient,source,ownerRow=null,recipientRow=null,recipientSlot=null){if(!recipient)return false;if(coopScopeIsSelf(e)){if(ownerRow!=null&&recipientRow!=null&&ownerRow!==recipientRow)return false;if(recipientSlot!=null&&recipientSlot<source)return false}if(coopScopeIsLeader(e)&&source!==0)return false;return matches(norm(recipient.details?.attribute),e?.applierAttribute??e?.applier??'全')}
function coopEffectApplies(x,attacker,enemy){return coopAllyMatchesEffect(x.effect,x.owner,attacker,x.source,x.deckRow,x.recipientRow,x.recipientSlot)&&targetMatches(x.effect,enemy.attribute)}
function coopAvailableSkills(deck,slot,enemyAttr){let active=[],shorten=0,activated=[];for(let source=0;source<=slot;source++){let owner=deck[source];if(!owner)continue;let turn=Number(owner.details?.skillTurn??0);if(!Number.isFinite(turn))turn=0;let availableTurn=source+shorten;if(turn>availableTurn)continue;let effects=skillEffectsOf(owner);activated.push({owner,source,turn,availableTurn,effects});for(let e of effects)if(coopStructuredEffectValid(e)&&en(e)==='短縮'&&coopAllyMatchesEffect(e,owner,deck[slot]||owner,source))shorten+=shortenValue(e);for(let e of effects){if(!coopStructuredEffectValid(e)||en(e)==='短縮')continue;let duration=effectDuration(e);if(source+duration>slot)active.push({effect:e,owner,source,duration,remaining:source+duration-slot})}}return{active,shorten,activated}}
function coopAllDeckSkills(slot,recipient,enemyAttr='',recipientRow=null){let active=[],shorten=0,sources=[];for(let row=0;row<coopVisibleRows;row++){let deck=coopDecks[row];if(!deck?.some(Boolean))continue;let state=coopAvailableSkills(deck,slot,enemyAttr);shorten+=state.shorten;for(let x of state.active)active.push({...x,deckRow:row,recipientRow,recipientSlot:slot});sources.push({row,state})}return{active,shorten,sources}}
function coopConditionText(value,fallback='指定なし'){let v=String(value??'').trim();return v||fallback}
function coopAllyCondition(e){let scope=coopConditionText(e?.applier,'味方'),attr=coopConditionText(e?.applierAttribute,'全');return `${scope} / 味方属性:${attr}`}
function coopEnemyCondition(e){return `敵属性:${coopConditionText(e?.targetAttribute,'全')}`}
function coopRecipientMatches(x,recipient){return coopAllyMatchesEffect(x.effect,x.owner,recipient,x.source,x.deckRow,x.recipientRow,x.recipientSlot)}
function coopAppliedSkillLabel(x,recipient,slot){if(!coopRecipientMatches(x,recipient))return null;let e=x.effect,n=en(e),v=amt(e),remaining=Math.max(1,x.remaining??(x.source+effectDuration(e)-slot)),effect='';if(n==='攻撃力アップ'&&Number.isFinite(v))effect=`攻撃力${fmt(v)}%増加`;else if(n==='連撃')effect=`${Math.max(1,Math.floor(raw(e.value??e.amount)))}回連撃`;else if(n==='全体攻撃')effect='全体攻撃';else return null;return {owner:x.owner?.name||'不明',duration:`${remaining}ターン`,effect,ally:coopAllyCondition(e),enemy:coopEnemyCondition(e)}}
function coopSkillMergeKey(x){return [x.duration,x.effect,x.ally,x.enemy].join('|')}
function toggleCoopSkillDetail(row,slot,box){let shouldOpen=box.hidden;document.querySelectorAll('.coop-skill-detail').forEach(x=>x.hidden=true);if(!shouldOpen)return;let recipient=coopDecks[row][slot];if(!recipient){box.innerHTML='<section><p>キャラを選択してください</p></section>';box.hidden=false;return}let skill=coopAllDeckSkills(slot,recipient,'',row),rawItems=skill.active.map(x=>{let item=coopAppliedSkillLabel(x,recipient,slot);return item?{...item,deckRow:x.deckRow}:null}).filter(Boolean),merged=new Map();for(let item of rawItems){let key=coopSkillMergeKey(item),entry=merged.get(key);if(!entry){entry={...item,count:0,sources:[]};merged.set(key,entry)}entry.count++;entry.sources.push(`デッキ${item.deckRow+1}/${item.owner}`)}let items=[...merged.values()],sameCount=rawItems.filter(x=>x.deckRow===row).length,otherCount=rawItems.length-sameCount,html=items.map(x=>`<article class="coop-applied-skill"><b>${esc(x.duration)}の間、${esc(x.effect)}${x.count>1?` ×${x.count}件`:''}</b><small>発動元: ${esc(x.sources.join('、'))}</small><small>適用条件: ${esc(x.ally)} / ${esc(x.enemy)}</small></article>`).join('');box.innerHTML=`<section><b>${esc(recipient.name||`${slot+1}枠目のキャラ`)}</b><small>累積短縮: ${skill.shorten} / 同じデッキ由来: ${sameCount}件 / 他デッキ由来: ${otherCount}件</small><div>${html||'<p>適用中のスキルなし</p>'}</div></section>`;box.hidden=false}
function coopDamage(c,enemy,skill){if(!c||!enemy?.hp)return 0;let d=c.details||{},power=Number(d.limitPower??d.power??0),attr=norm(d.attribute),atk=1,hits=1,all=1;for(let x of skill.active){let e=x.effect;if(!coopEffectApplies(x,c,enemy))continue;let n=en(e),v=amt(e);if(n==='攻撃力アップ'&&Number.isFinite(v))atk*=1+v/100;else if(n==='連撃')hits+=Math.max(1,Math.floor(raw(e.value??e.amount)))-1;else if(n==='全体攻撃')all=5}return Math.floor(power*COOP_DAMAGE_BASE*(MATCH[attr]?.[enemy.attribute]??1)*atk*hits*all)}
function permutations(a){if(a.length<2)return[a.slice()];let out=[];a.forEach((v,i)=>permutations(a.slice(0,i).concat(a.slice(i+1))).forEach(p=>out.push([v,...p])));return out}
function layerOutcome(order,layer){let initial=[0,1,2].map(pos=>coopScaledHp(layer*3+pos)),configured=initial.some(Boolean);if(!configured)return{configured:false,all:false,some:false,fail:null,success:null};let all=true,some=false,fail=null,success=null;function finish(hps,path){let ok=hps.every(h=>h<=0),record={order:order.slice(),targets:path.slice(),remaining:hps.slice()};all=all&&ok;some=some||ok;if(ok&&!success)success=record;if(!ok&&!fail)fail=record}function walk(step,hps,path){let living=hps.map((hp,pos)=>hp>0?pos:-1).filter(pos=>pos>=0);if(!living.length){finish(hps,path);return}if(step===order.length){finish(hps,path);return}let r=order[step],c=coopDecks[r][layer];if(!c){walk(step+1,hps,path.concat(null));return}for(let pos of living){let i=layer*3+pos,e={...coopEnemies[i],hp:hps[pos]},skill=coopAllDeckSkills(layer,c,e.attribute,r),damage=coopDamage(c,e,skill),next=hps.slice();next[pos]=Math.max(0,next[pos]-damage);walk(step+1,next,path.concat(pos))}}walk(0,initial,[]);return{configured:true,all,some,fail,success}}
function coopFailureText(layer,x){if(!x?.fail)return'';let order=x.fail.order.map(r=>`D${r+1}`).join('→'),targets=x.fail.targets.map(p=>p==null?'攻撃なし':`${p+1}枠`).join('→'),remaining=x.fail.remaining.map((hp,i)=>`${i+1}枠:${Math.ceil(hp).toLocaleString()}`).join('、');return `${layer+1}層: デッキ順 ${order} / 攻撃先 ${targets} / 最終残HP ${remaining}`}
function calculateCoop(){if(!$('coopClearResult'))return;let activeRows=Array.from({length:coopVisibleRows},(_,r)=>r).filter(r=>coopDecks[r].some(Boolean));document.querySelectorAll('.coop-row-result').forEach(q=>q.textContent='');if(!activeRows.length){$('coopClearResult').textContent='味方デッキを入力してください';$('coopDamageResult').textContent='';$('coopResultDetails').textContent='';return}let orders=permutations(activeRows),layerAll=Array(5).fill(true),layerSome=Array(5).fill(false),configured=Array(5).fill(false),witnesses=Array(5).fill(null);for(let order of orders)for(let layer=0;layer<5;layer++){let x=layerOutcome(order,layer);if(!x.configured)continue;configured[layer]=true;layerAll[layer]=layerAll[layer]&&x.all;layerSome[layer]=layerSome[layer]||x.some;if(x.fail&&!witnesses[layer])witnesses[layer]=x}let bad=[],random=[];for(let i=0;i<5;i++)if(configured[i]){if(!layerSome[i])bad.push(i+1);else if(!layerAll[i])random.push(i+1)}let status=!configured.some(Boolean)?'敵を入力してください':bad.length?'撃破不可能':random.length?'ランダム撃破':'確定撃破';$('coopClearResult').textContent=status;$('coopDamageResult').textContent=bad.length?`${bad.join('・')}層目で撃破不可能`:random.length?`${random.join('・')}層目で結果が変動`:'すべてのデッキ順・攻撃対象で撃破可能';let problemLayers=(bad.length?bad:random).map(n=>n-1),reasons=problemLayers.map(layer=>coopFailureText(layer,witnesses[layer])).filter(Boolean);$('coopResultDetails').innerHTML=`<div>判定対象: ${activeRows.length}デッキ / デッキ順 ${orders.length}通り / 各層の攻撃対象3通り</div>${reasons.length?`<details class="coop-random-reason" open><summary>${bad.length?'撃破不可能':'ランダム撃破'}となる組合せ例</summary>${reasons.map(esc).join('<br>')}</details>`:''}`}
function recommendCoopDecks(){for(let slot=0;slot<5;slot++)coopDecks[0][slot]=coopEnemies[slot*3+1].character;syncCoopVisibleRows();renderCoopDecks();saveCoopState()}
function deleteCoopDeck(row){if(row<1||row>=coopVisibleRows)return;coopDecks.splice(row,1);coopDecks.push(Array(COOP_SLOTS).fill(null));coopVisibleRows=Math.max(1,coopVisibleRows-1);if(coopClipboard===row)coopClipboard=null;else if(coopClipboard>row)coopClipboard--;renderCoopDecks();saveCoopState()}
function coopPower(c){return Number(c?.details?.limitPower??c?.details?.power??0)||0}
function coopTurnZeroSkill(c){let turn=Number(c?.details?.skillTurn??0);if(turn!==0)return{active:[],shorten:0};let active=skillEffectsOf(c).filter(e=>coopStructuredEffectValid(e)&&['攻撃力アップ','連撃'].includes(en(e))).map(e=>({effect:e,owner:c,source:0,duration:effectDuration(e),remaining:effectDuration(e),deckRow:0,recipientRow:0,recipientSlot:0}));return{active,shorten:0}}
function coopProposalHasSelfApplier(c){return skillEffectsOf(c).filter(coopStructuredEffectValid).some(e=>coopScopeIsSelf(e))}
function coopFirstSkillEligible(c){let effects=skillEffectsOf(c).filter(coopStructuredEffectValid);if(['N','伝'].includes(c?.details?.rare))return false;if(!effects.length)return true;return Number(c?.details?.skillTurn??0)===0&&effects.every(e=>['攻撃力アップ','連撃'].includes(en(e)))}
function coopOpeningDamage(c,e){return coopDamage(c,{...e,hp:coopScaledHp(coopEnemies.indexOf(e))},coopTurnZeroSkill(c))}
function coopOpeningFloor(c){return Math.min(...[0,1,2].map(pos=>{let e=coopEnemies[pos];return e.character?coopOpeningDamage(c,e):-1}))}
function coopFirstCandidate(c){let floor=coopOpeningFloor(c);return floor>=0&&[0,1,2].every(pos=>floor>=coopScaledHp(pos))}
function coopRestrictionRank(c){let effects=skillEffectsOf(c).filter(coopStructuredEffectValid),rank=0;for(let e of effects){let req=String(e.applierAttribute??e.applier??'全');if(/全員|味方全員|すべて|全/.test(req))rank-=10;else if(/火水|水風|風火/.test(req))rank+=2;else if(/火|水|風/.test(req))rank+=1}return rank}
function coopDeck1HasShortenBefore(slot){let deck=coopDecks[0]||[];for(let source=0;source<slot;source++){let owner=deck[source];if(!owner)continue;let turn=Number(owner.details?.skillTurn??0);if(!Number.isFinite(turn))turn=0;if(turn>source)continue;if(skillEffectsOf(owner).some(e=>coopStructuredEffectValid(e)&&en(e)==='短縮'&&shortenValue(e)>0))return true}return false}
function coopProposalTurnAllowed(slot,turn){let shortened=coopDeck1HasShortenBefore(slot),ranges=shortened?{1:[1],2:[1,2,3,4],3:[3,4,5,6],4:[3,4,5,6,7,8]}:{1:[1],2:[1,2],3:[2,3],4:[3,4]};return (ranges[slot]||[]).includes(Number(turn))}
function coopProposalPool(slot){let seen=new Map();for(let c of chars){let effects=skillEffectsOf(c).filter(coopStructuredEffectValid),combat=effects.filter(e=>['攻撃力アップ','連撃','全体攻撃'].includes(en(e)));if(['N','伝'].includes(c?.details?.rare)||!combat.length||(slot>=2&&coopProposalHasSelfApplier(c))||!coopProposalTurnAllowed(slot,c.details?.skillTurn))continue;let sig=[norm(c.details?.attribute),c.details?.skillTurn??'',...effects.map(e=>[en(e),e.value,e.duration,e.applier,e.applierAttribute,e.target,e.targetAttribute].join(':')).sort()].join('|'),prev=seen.get(sig);if(!prev||coopPower(c)>coopPower(prev)||(coopPower(c)===coopPower(prev)&&Number(c.details?.id??c.id)<Number(prev.details?.id??prev.id)))seen.set(sig,c)}return [...seen.values()].sort((a,b)=>coopPower(b)-coopPower(a)||coopRestrictionRank(a)-coopRestrictionRank(b)||Number(a.details?.id??a.id)-Number(b.details?.id??b.id))}
function coopProposalDeck(candidate,row){let deck=candidate.slice();if(row===1)deck[4]=coopEnemies[12].character;if(row===2)deck[4]=coopEnemies[14].character;return deck}
function coopProposalLayerCertain(order,layer){let initial=[0,1,2].map(pos=>coopScaledHp(layer*3+pos));if(!initial.some(Boolean))return false;function walk(step,hps){let living=hps.map((hp,pos)=>hp>0?pos:-1).filter(pos=>pos>=0);if(!living.length)return true;if(step===order.length)return false;let row=order[step],attacker=coopDecks[row][layer];if(!attacker)return walk(step+1,hps);for(let pos of living){let i=layer*3+pos,enemy={...coopEnemies[i],hp:hps[pos]},skill=coopAllDeckSkills(layer,attacker,enemy.attribute,row),damage=coopDamage(attacker,enemy,skill),next=hps.slice();next[pos]=Math.max(0,next[pos]-damage);if(!walk(step+1,next))return false}return true}return walk(0,initial)}
function coopProposalWorks(candidate,count){let backup=coopDecks.map(x=>x.slice()),visible=coopVisibleRows;try{coopDecks[0]=backup[0].slice();for(let r=1;r<=count;r++)coopDecks[r]=coopProposalDeck(candidate,r);coopVisibleRows=count+1;let orders=permutations(Array.from({length:count+1},(_,i)=>i));for(let order of orders)for(let layer=0;layer<5;layer++)if(!coopProposalLayerCertain(order,layer))return false;return true}finally{coopDecks=backup;coopVisibleRows=visible}}
function coopProposalOverkill(deck){let total=0;for(let slot=0;slot<5;slot++){let c=deck[slot];if(!c)continue;let skill=coopAvailableSkills(deck,slot,'');for(let pos=0;pos<3;pos++){let i=slot*3+pos,e={...coopEnemies[i],hp:coopScaledHp(i)},damage=coopDamage(c,e,skill);total+=Math.max(0,damage-e.hp)}}return total}
function renderCoopProposalDecks(items){let section=$('coopProposalResults'),grid=$('coopProposalGrid');if(!section||!grid)return;grid.innerHTML='';section.hidden=!items.length;items.forEach((item,index)=>{let card=document.createElement('article');card.className='coop-proposal-card';card.innerHTML=`<b>${index+1}</b><div class="coop-proposal-images">${item.deck.map(c=>c?`<img src="${esc(c.imageUrl||'')}" alt="${esc(c.name||'')}">`:'<span></span>').join('')}</div>`;grid.append(card)})}
function keepTopCoopProposals(list,item){list.push(item);list.sort((a,b)=>b.overkill-a.overkill);if(list.length>10)list.length=10}
function coopYield(){return new Promise(resolve=>setTimeout(resolve,0))}
function coopSetProposalProgress(text,busy){let button=$('coopPropose');if(button){button.disabled=busy;button.textContent=busy?'提案を探索中…':'デッキキャラ提案'}if(busy)$('coopClearResult').textContent='提案を探索中';if(text)$('coopDamageResult').textContent=text}
function coopProposalCombinationCount(pools,first){let count=0;for(let a of pools[1])for(let b of pools[2])for(let c of pools[3])for(let d of pools[4]){let keys=[first,a,b,c,d].map(coopCharacterKey).filter(Boolean);if(new Set(keys).size===keys.length)count++}return count}
async function proposeCoopDecks(){recommendCoopDecks();renderCoopProposalDecks([]);let all=chars.filter(c=>c?.details?.rare!=='N'&&coopPower(c)>0&&coopFirstSkillEligible(c)),sure=all.filter(coopFirstCandidate).sort((a,b)=>coopPower(a)-coopPower(b)||Number(a.details?.id??a.id)-Number(b.details?.id??b.id)),first=sure[0]||all.sort((a,b)=>coopOpeningFloor(b)-coopOpeningFloor(a)||coopPower(b)-coopPower(a)||Number(a.details?.id??a.id)-Number(b.details?.id??b.id))[0];if(!first){$('coopClearResult').textContent='提案不可';$('coopDamageResult').textContent='初手候補がありません';return}let pools=[null,coopProposalPool(1),coopProposalPool(2),coopProposalPool(3),coopProposalPool(4)],top=[],checked=0,lastYield=performance.now(),total=coopProposalCombinationCount(pools,first);if(pools.slice(1).some(pool=>!pool.length)){$('coopClearResult').textContent='提案不可';$('coopDamageResult').textContent='指定された必要ターン範囲に該当する候補がない枠があります';return}coopSetProposalProgress(`全${total.toLocaleString()}件を探索 / ダメージ過剰量が大きい順`,true);try{for(let ai=0;ai<pools[1].length;ai++)for(let bi=0;bi<pools[2].length;bi++)for(let ci=0;ci<pools[3].length;ci++)for(let di=0;di<pools[4].length;di++){let deck=[first,pools[1][ai],pools[2][bi],pools[3][ci],pools[4][di]],keys=deck.map(coopCharacterKey).filter(Boolean);if(new Set(keys).size!==keys.length)continue;let repeats=coopProposalWorks(deck,3)?3:(coopProposalWorks(deck,4)?4:0);checked++;if(repeats)keepTopCoopProposals(top,{deck:deck.slice(),repeats,overkill:coopProposalOverkill(deck)});let now=performance.now();if(checked%10===0||now-lastYield>=12){coopSetProposalProgress(`${checked.toLocaleString()} / ${total.toLocaleString()}件確認 / 提案${top.length}件`,true);await coopYield();lastYield=performance.now()}}renderCoopProposalDecks(top);if(!top.length){$('coopClearResult').textContent='提案不可';$('coopDamageResult').textContent='指定条件で確定撃破の提案デッキが見つかりませんでした';return}$('coopClearResult').textContent='提案完了';$('coopDamageResult').textContent=`ダメージ過剰量が大きい順に${top.length}デッキ表示 / 全${total.toLocaleString()}件探索`}finally{coopSetProposalProgress('',false)}}
function resetCoopDecks(){renderCoopProposalDecks([]);coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(5).fill(null));coopVisibleRows=1;coopClipboard=null;renderCoopDecks();saveCoopState()}
function resetCoop(){renderCoopProposalDecks([]);coopEnemies=Array.from({length:15},()=>({character:null,hp:0,attribute:'火'}));coopDecks=Array.from({length:COOP_MAX_ROWS},()=>Array(5).fill(null));coopVisibleRows=1;coopClipboard=null;coopDetailMode=false;coopStoredState=null;try{localStorage.removeItem(COOP_STORAGE_KEY)}catch{}syncCoopDetailMode();renderCoopEnemies();renderCoopDecks()}
