const $=id=>document.getElementById(id),ATTRS=['火','水','風','火水','水風','風火','全'];
const MATCH={'火':{'火':2/3,'水':1/3,'風':1,'火水':1/2,'水風':2/3,'風火':5/6,'全':2/3},'水':{'火':1,'水':2/3,'風':1/3,'火水':5/6,'水風':1/2,'風火':2/3,'全':2/3},'風':{'火':1/3,'水':1,'風':2/3,'火水':2/3,'水風':5/6,'風火':1/2,'全':2/3},'火水':{'火':5/6,'水':1/2,'風':2/3,'火水':2/3,'水風':7/12,'風火':3/4,'全':2/3},'水風':{'火':2/3,'水':5/6,'風':1/2,'火水':3/4,'水風':2/3,'風火':7/12,'全':2/3},'風火':{'火':1/2,'水':2/3,'風':5/6,'火水':7/12,'水風':3/4,'風火':2/3,'全':2/3},'全':{'火':2/3,'水':2/3,'風':2/3,'火水':2/3,'水風':2/3,'風火':2/3,'全':2/3}};
let chars=[],tierData=null,current=-1,detailOrder=[],pickerRole=null,fromPicker=false,lastDirection=1,selected={attacker:null,defender:null},skillEnabled={attacker:false,defender:false},detailMode=false,lastResult=null,ghostData=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canon=s=>String(s??'').replace(/火風/g,'風火').replace(/属性/g,'').trim();
const fmt=n=>{n=Math.round((Number(n)||0)*1e6)/1e6;return Number.isInteger(n)?String(n):String(n).replace(/0+$/,'').replace(/\.$/,'')};
let numericFocusScroll=null;
function keepNumericViewport(input){input.addEventListener('focus',()=>{numericFocusScroll={x:scrollX,y:scrollY}});input.addEventListener('blur',()=>{if(!numericFocusScroll)return;let pos=numericFocusScroll;numericFocusScroll=null;requestAnimationFrame(()=>scrollTo(pos.x,pos.y))})}
addEventListener('DOMContentLoaded',init);
function init(){ATTRS.forEach(a=>{$('attackerAttribute').add(new Option(a,a));$('defenderAttribute').add(new Option(a,a))});for(let n=0;n<=10;n++)$('survivalTurns').add(new Option(`${n}ターン（×1.3^${n}）`,n));keepNumericViewport($('attackerPower'));keepNumericViewport($('defenderHp'));makeFields('attackBuffFields','attackBuffRate','追加攻撃力増加',4);makeFields('extraHitFields','extraHit','追加連撃効果',3,'回');makeFields('cutRateFields','cutRate','追加軽減率',6);makeFields('extraHealFields','extraHeal','追加回復効果',3);bind();loadData();calculate()}
function makeFields(box,prefix,label,count,unit='%'){for(let i=1;i<=count;i++){let l=document.createElement('label');l.hidden=i>1;l.textContent=`${label}${i}（${unit}）`;let q=document.createElement('input');q.type='number';q.step='any';keepNumericViewport(q);q.id=prefix+i;q.placeholder=i===1?(prefix==='extraHit'?'例: 5':'例: 80'):'';q.oninput=()=>{progress(prefix,count);calculate()};l.append(q);$(box).append(l)}}
function fieldCount(prefix){return prefix==='attackBuffRate'?4:prefix==='extraHit'||prefix==='extraHeal'?3:6}
function progress(prefix,count=fieldCount(prefix)){for(let i=2;i<=count;i++){let q=$(prefix+i),prev=$(prefix+(i-1)),show=prev.value!==''&&Number(prev.value)!==0;q.parentElement.hidden=!show;if(!show)q.value=''}}
function bind(){$('sidebar').classList.remove('open');$('menuToggle').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('attackerPicker').onclick=()=>openPicker('attacker');$('defenderPicker').onclick=()=>openPicker('defender');$('zkSearch').oninput=renderZukan;$('pickerSearch').oninput=renderPicker;['zkCostMin','zkCostMax','zkTurnMin','zkTurnMax','zkSort','zkSortDirection'].forEach(id=>$(id).oninput=renderZukanFilterResults);document.querySelectorAll('[name="zkAttribute"],[name="zkAttributeMode"],[name="zkRare"],[name="zkSkill"]').forEach(q=>q.onchange=renderZukanFilterResults);$('zkFilterClear').onclick=clearZukanFilters;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).hidden=true);document.querySelectorAll('#detailActions button').forEach(b=>b.onclick=()=>choose(b.dataset.role));$('detailPrev').onclick=()=>move(-1);$('detailNext').onclick=()=>move(1);$('swap').onclick=swap;$('attackerSkillBtn').onclick=()=>toggleSkill('attacker');$('defenderSkillBtn').onclick=()=>toggleSkill('defender');['attackerPower','defenderHp','attackerAttribute','defenderAttribute','answerSpeed','selfMode','attackerEvent','defenderEvent','questionLevel','survivalTurns','allAttack'].forEach(id=>$(id).oninput=calculate);$('tierBtn').onclick=execTier;$('downloadResult').onclick=downloadResult;$('resetAll').onclick=resetAll;$('detailMode').onclick=toggleDetailMode;syncDetailMode();for(let r of ['attacker','defender']){$(r+'ResetExceptCharacter').onclick=()=>resetExceptCharacter(r);$(r+'RemoveCharacter').onclick=()=>removeCharacter(r)}let confirmKeyDown=false;window.addEventListener('keydown',e=>{if($('detail').hidden||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable||e.repeat)return;let k=e.key.toLowerCase(),dir=0;if(k==='a'||k==='j'||e.key==='ArrowLeft')dir=-1;else if(k==='d'||k==='k'||e.key==='ArrowRight')dir=1;else if(e.key==='Enter'||e.key===' '){if(confirmKeyDown)return;confirmKeyDown=true;dir=lastDirection}else if(e.key==='Escape'){$('detail').hidden=true;return}if(dir){e.preventDefault();e.stopPropagation();move(dir)}},true);window.addEventListener('keyup',e=>{if(e.key==='Enter'||e.key===' ')confirmKeyDown=false},true)}
function showPage(n){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+n));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===n));$('sidebar').classList.remove('open')}
async function loadData(){try{let r=await fetch('zukan_beta.json',{cache:'no-store'}).then(x=>{if(!x.ok)throw Error(x.status);return x.json()});chars=Array.isArray(r)?r:(r.characters||[]);if(!chars.length)throw Error('charactersが空です');$('zkStatus').textContent='';renderZukan()}catch(error){chars=[];$('zkStatus').textContent='図鑑データを読み込めません';console.error(error)}try{tierData=await fetch('tier_all_patterns.json',{cache:'no-store'}).then(x=>{if(!x.ok)throw Error(x.status);return x.json()});Object.entries(tierData?.meta?.shibari||{}).forEach(([id,n])=>$('attribute').add(new Option(canon(n),id)));$('tierBtn').disabled=false;$('tierResult').textContent=''}catch(error){tierData=null;$('tierBtn').disabled=true;$('tierResult').textContent='Tierデータを読み込めませんでした';console.error(error)}}
function results(q=''){q=String(q).normalize('NFKC').replace(/[\s　]+/g,'').toLowerCase();return chars.map((c,i)=>({c,i})).filter(x=>!q||String(x.c.name||'').normalize('NFKC').replace(/[\s　]+/g,'').toLowerCase().includes(q))}
