/* 英語物語 対戦ツール: catalog */
function renderTree(items,box,opened,direct=false){let t={};items.forEach(x=>{let c=x.c,a=c.largeCategory||'未分類',b=c.middleCategory||'その他',s=c.smallCategory||'その他',h=c.heading||'';((((t[a]??={})[b]??={})[s]??={})[h]??=[]).push(x)});box.innerHTML='';Object.entries(t).forEach(([a,m])=>{let A=folder(a,'zk-b1 '+(a==='特殊ゆる'?'special':'normal'),opened),ab=A.lastChild;Object.entries(m).forEach(([b,sm])=>{let B=folder(b,'zk-b2',opened),bb=B.lastChild;Object.entries(sm).forEach(([s,hm])=>{if(b==='伝'){let z=document.createElement('div');z.className='zk-head';z.textContent=s;bb.append(z);Object.entries(hm).forEach(([h,list])=>{if(h&&h!=='その他'){let q=document.createElement('div');q.className='zk-head';q.textContent=h;bb.append(q)}let g=document.createElement('div');g.className='zk-grid';list.forEach(x=>g.append(card(x.c,x.i,opened,null,direct)));bb.append(g)});return}let S=s==='その他'?null:folder(s,'zk-b3',opened),sb=S?S.lastChild:bb;Object.entries(hm).forEach(([h,list])=>{if(h&&h!=='その他'){let z=document.createElement('div');z.className='zk-head';z.textContent=h;sb.append(z)}let g=document.createElement('div');g.className='zk-grid';list.forEach(x=>g.append(card(x.c,x.i,opened,null,direct)));sb.append(g)});if(S)bb.append(S)});ab.append(B)});box.append(A)})}
function folder(name,cls,o){let w=document.createElement('div'),b=document.createElement('button'),d=document.createElement('div'),a=document.createElement('span');w.className='zk-l1';b.className=cls;a.textContent=o?'▼':'▶';d.className='zk-body'+(o?' open':'');b.append(document.createTextNode(name),a);b.onclick=()=>{let x=d.classList.toggle('open');a.textContent=x?'▼':'▶'};w.append(b,d);return w}
function sortCardLabel(c){let d=c.details||{},sort=$('zkSort')?.value;if(!sort)return c.name||'';if(sort==='hp')return `HP ${Number(d.limitHp??d.hp??0).toLocaleString()}`;if(sort==='power')return `攻撃力 ${Number(d.limitPower??d.power??0).toLocaleString()}`;if(sort==='total')return `HP+攻撃力 ${(Number(d.limitHp??d.hp??0)+Number(d.limitPower??d.power??0)).toLocaleString()}`;if(sort==='cost')return `Cost ${Number(d.cost??0).toLocaleString()}`;if(sort==='skillTurn')return `スキルターン ${Number(d.skillTurn??0).toLocaleString()}`;if(sort==='rare')return `レア ${d.rare||''}`;return c.name||''}
function card(c,i,p,label=null,direct=false){let b=document.createElement('button'),im=document.createElement('img'),sm=document.createElement('small');b.className='zk-card';b.dataset.charIndex=String(i);im.loading='lazy';im.decoding='async';im.width=64;im.height=64;im.src=c.imageUrl||'';sm.textContent=label??c.name??'';b.append(im,sm);b.onclick=()=>{if(direct){current=i;fromPicker=true;choose('picker');return}let box=b.closest('#zkBox,#zkFilteredBox'),order=box?[...box.querySelectorAll('.zk-card[data-char-index]')].map(x=>Number(x.dataset.charIndex)):null;openDetail(i,p,order&&order.length?order:null)};return b}
function skillEffectsOf(c){return Array.isArray(c?.details?.skillEffects)?c.details.skillEffects:[]}
function pickerSkillAllowed(c){if(pickerPurpose!=='skill')return true;let allowed=pickerRole==='attacker'?new Set(['攻撃力アップ','連撃','全体攻撃']):new Set(['シールド','回復','集中','かわす']);return skillEffectsOf(c).some(e=>allowed.has(en(e)))}
function pickerSource(items){return items.filter(x=>pickerSkillAllowed(x.c))}
function skillAttrOrder(value){let s=canon(value);if(!s||['全','全員','味方全員','敵全員','すべて'].includes(s))return 0;if(s.includes('火'))return 1;if(s.includes('水'))return 2;if(s.includes('風'))return 3;return 4}
function skillRelationAttrs(e){let ally=e?.applierAttribute??e?.applier??e?.['適用者']??'',enemy=e?.targetAttribute??e?.target??e?.['対象者']??'';return [skillAttrOrder(ally),skillAttrOrder(enemy)]}
function skillTypeOrder(e){let n=en(e),order={'連撃':4,'全体攻撃':5,'シールド':6,'回復':7,'色変':8,'短縮':9,'遅延':10,'集中':11,'かわす':12};if(n!=='攻撃力アップ')return order[n]??99;let applier=String(e?.applierAttribute??e?.applier??e?.['適用者']??''),target=String(e?.targetAttribute??e?.target??e?.['対象者']??'');if(/自身|自分/.test(applier)||/自身|自分/.test(target))return 3;if(/全員|味方全員/.test(applier)||/全員|味方全員/.test(target))return 2;return 1}
function skillSortKey(c){let es=skillEffectsOf(c);if(!es.length)return [0,0,0];let best=null;for(let e of es){let type=skillTypeOrder(e),attrs=skillRelationAttrs(e),key=type===9?[type,attrs[1],attrs[0]]:[type,attrs[0],attrs[1]];if(!best||key.some((v,i)=>v!==best[i]&&v<best[i]&&key.slice(0,i).every((x,j)=>x===best[j])))best=key}return best||[99,4,4]}
function characterIdOrder(x){let v=Number(x?.c?.id??x?.c?.details?.id);return Number.isFinite(v)?v:Number.MAX_SAFE_INTEGER}
function compareSkillTurn(a,b){let at=Number(a.c.details?.skillTurn),bt=Number(b.c.details?.skillTurn);at=Number.isFinite(at)?at:Number.MAX_SAFE_INTEGER;bt=Number.isFinite(bt)?bt:Number.MAX_SAFE_INTEGER;if(at!==bt)return at-bt;let ak=skillSortKey(a.c),bk=skillSortKey(b.c);for(let i=0;i<ak.length;i++)if(ak[i]!==bk[i])return ak[i]-bk[i];return a.i-b.i}
function checkedValues(name){return [...document.querySelectorAll(`[name="${name}"]:checked`)].map(q=>q.value)}
function zukanFilterActive(){return checkedValues('zkAttribute').length>0||checkedValues('zkRare').length>0||checkedValues('zkSkill').length>0||['zkCostMin','zkCostMax','zkTurnMin','zkTurnMax','zkSort'].some(id=>$(id).value)}
function attributeMatches(value,selected,mode){let cur=canon(value);if(!selected.length)return true;if(mode==='exact')return selected.includes(cur);return selected.some(a=>cur==='全'||cur.includes(a))}
function zukanFilteredResults(){let r=chars.map((c,i)=>({c,i})),attrs=checkedValues('zkAttribute'),attrMode=document.querySelector('[name="zkAttributeMode"]:checked')?.value||'include',rares=checkedValues('zkRare'),cmin=raw($('zkCostMin').value),cmax=raw($('zkCostMax').value),skills=checkedValues('zkSkill'),tmin=raw($('zkTurnMin').value),tmax=raw($('zkTurnMax').value),sort=$('zkSort').value,dir=$('zkSortDirection').value==='asc'?1:-1,rank={N:1,R:2,CR:3,ZR:4,MZR:5,'伝':6};r=r.filter(x=>{let d=x.c.details||{},effects=d.skillEffects||[];return attributeMatches(d.attribute,attrs,attrMode)&&(!rares.length||rares.includes(d.rare))&&(!Number.isFinite(cmin)||Number(d.cost)>=cmin)&&(!Number.isFinite(cmax)||Number(d.cost)<=cmax)&&(!skills.length||skills.some(skill=>effects.some(e=>en(e)===skill)))&&(!Number.isFinite(tmin)||Number(d.skillTurn)>=tmin)&&(!Number.isFinite(tmax)||Number(d.skillTurn)<=tmax)});if(sort==='skillTurn')r.sort(compareSkillTurn);else if(sort)r.sort((a,b)=>{let ad=a.c.details||{},bd=b.c.details||{},av=sort==='total'?Number(ad.limitHp??ad.hp??0)+Number(ad.limitPower??ad.power??0):sort==='rare'?(rank[ad.rare]||0):Number(ad[sort]??0),bv=sort==='total'?Number(bd.limitHp??bd.hp??0)+Number(bd.limitPower??bd.power??0):sort==='rare'?(rank[bd.rare]||0):Number(bd[sort]??0);return(av-bv)*dir||characterIdOrder(a)-characterIdOrder(b)||a.i-b.i});return r}
function clearZukanFilters(){document.querySelectorAll('[name="zkAttribute"],[name="zkRare"],[name="zkSkill"]').forEach(q=>q.checked=false);let include=document.querySelector('[name="zkAttributeMode"][value="include"]');if(include)include.checked=true;['zkCostMin','zkCostMax','zkTurnMin','zkTurnMax'].forEach(id=>$(id).value='');$('zkSort').value='';$('zkSortDirection').value='desc';renderZukanFilterResults()}
function renderZukanFilterResults(){let active=zukanFilterActive(),section=$('zkFilterResults');section.hidden=!active;if(!active){$('zkFilteredBox').innerHTML='';$('zkFilteredCount').textContent='';return}let source=zukanFilteredResults(),seen=new Set(),r=source.filter(x=>{let key=x.c.id??x.c.details?.id??x.i;if(seen.has(key))return false;seen.add(key);return true}),box=$('zkFilteredBox');$('zkFilteredCount').textContent=`${r.length}件`;box.innerHTML='';r.forEach(x=>box.append(card(x.c,x.i,false,sortCardLabel(x.c))))}
function renderZukan(){let r=results($('zkSearch').value);$('zkCount').textContent=`${r.length}件 / 全${chars.length}体`;renderTree(r,$('zkBox'),Boolean($('zkSearch').value));renderZukanFilterResults()}
function openPicker(r,purpose='character'){pickerRole=r;pickerPurpose=purpose;$('pickerTitle').textContent=purpose==='skill'?'使用する他キャラのスキルを選択':(r==='attacker'?'攻撃キャラ':'攻撃対象キャラ')+'を選択';$('pickerSearch').value='';ensurePickerTools();renderPicker();$('picker').hidden=false}
function renderPicker(){let q=pickerSource(results($('pickerSearch').value));renderTree(q,$('pickerBox'),Boolean($('pickerSearch').value),true);renderPickerTemporary();renderPickerFilterResults()}
function theme(attr){const colors={火:['#e53935','#ffe7e5'],水:['#1976d2','#e3f0ff'],風:['#7cbf19','#edf8d8']},parts=['火','水','風'].filter(x=>canon(attr).includes(x));if(!parts.length)return['#6c757d','#6c757d','#f1f3f5'];const accent=colors[parts[0]][0],bar=parts.length>1?'linear-gradient(135deg,'+parts.map(x=>colors[x][0]).join(',')+')':accent,soft=parts.length>1?'linear-gradient(135deg,'+parts.map(x=>colors[x][1]).join(',')+')':colors[parts[0]][1];return[accent,bar,soft]}
function openDetail(i,p=false,o=null){let c=chars[i],d=c?.details||{};if(!c)return;current=i;fromPicker=p;detailOrder=o||results(p?$('pickerSearch').value:$('zkSearch').value).map(x=>x.i);let [accent,bar,soft]=theme(d.attribute),panel=$('detail').querySelector('.detail-modal');panel.style.setProperty('--accent',accent);panel.style.setProperty('--bar',bar);panel.style.setProperty('--soft',soft);$('detailImage').src=c.imageUrl||'';$('detailName').textContent=c.name||'';$('detailMeta').textContent=[d.rare,canon(d.attribute),d.cost!=null?'Cost '+d.cost:null].filter(Boolean).join(' / ');$('detailStats').innerHTML=[['無凸HP',d.hp],['無凸Power',d.power],['完凸HP',d.limitHp],['完凸Power',d.limitPower]].filter(x=>x[1]!=null).map(x=>`<div><span>${x[0]}</span><b>${Number(x[1]).toLocaleString()}</b></div>`).join('');$('detailSkill').textContent=d.skill||'';$('detailTurn').textContent=d.skillTurn!=null?'必要ターン '+d.skillTurn:'';document.querySelector('[data-role="attacker"]').hidden=p;document.querySelector('[data-role="defender"]').hidden=p;document.querySelector('[data-role="picker"]').hidden=!p;syncDetailTemporaryButton();$('detail').hidden=false}
function move(d){lastDirection=d<0?-1:1;let p=detailOrder.indexOf(current);if(p>=0&&detailOrder.length)openDetail(detailOrder[(p+lastDirection+detailOrder.length)%detailOrder.length],fromPicker,detailOrder)}
function choose(r){if(r==='picker')r=pickerRole;if(fromPicker&&pickerPurpose==='skill'){addBorrowedSkill(r,chars[current]);$('detail').hidden=$('picker').hidden=true;showPage('calculator');return}setCharacter(r,chars[current]);$('detail').hidden=$('picker').hidden=true;showPage('calculator')}
function norm(x){let s=canon(x);return ATTRS.filter(a=>a!=='全').sort((a,b)=>b.length-a.length).find(a=>s.includes(a))||'全'}
function setCharacter(r,c,keep=false){selected[r]=c;if(!keep)skillEnabled[r]=false;let d=c.details||{},p=$(r+'Picker');p.querySelector('.portrait').style.backgroundImage=`url("${String(c.imageUrl||'').replace(/"/g,'')}")`;p.querySelector('strong').textContent=c.name||'';p.querySelector('small').textContent=[d.rare,canon(d.attribute),d.cost!=null?'Cost '+d.cost:null].filter(Boolean).join(' / ');$(r==='attacker'?'attackerPower':'defenderHp').value=Number(r==='attacker'?(d.limitPower??d.power??0):(d.limitHp??d.hp??0));$(r+'Attribute').value=norm(d.attribute);$(r+'Event').value='1';if(r==='attacker'&&!keep)$('survivalTurns').value='0';$(r+'Skill').textContent=d.skill||'スキルなし';$(r+'SkillBtn').disabled=!d.skill;syncSkill(r);calculate()}


/* 一時保存・共通選択機能 */
function characterKey(c){return String(c?.id??c?.details?.id??c?.name??'')}
function loadTemporaryCharacters(){try{let ids=JSON.parse(localStorage.getItem('eigoTemporaryCharacters')||'[]');tempCharacters=[...new Set((Array.isArray(ids)?ids:[]).map(String))]}catch{tempCharacters=[]}renderTemporaryCharacters()}
function persistTemporaryCharacters(){tempCharacters=[...new Set(tempCharacters.map(String))];localStorage.setItem('eigoTemporaryCharacters',JSON.stringify(tempCharacters));renderTemporaryCharacters();renderPickerTemporary();syncDetailTemporaryButton()}
function isTemporary(c){return tempCharacters.includes(characterKey(c))}
function toggleCurrentTemporary(){let c=chars[current];if(!c)return;let k=characterKey(c),i=tempCharacters.indexOf(k);if(i>=0)tempCharacters.splice(i,1);else tempCharacters.push(k);persistTemporaryCharacters()}
function syncDetailTemporaryButton(){let b=$('detailTemp'),c=chars[current];if(!b||!c)return;b.textContent=isTemporary(c)?'一時保存から削除':'一時保存する';b.classList.toggle('danger',isTemporary(c))}
function temporaryEntries(){let set=new Set(tempCharacters),seen=new Set();return chars.map((c,i)=>({c,i})).filter(x=>{let k=characterKey(x.c);if(!set.has(k)||seen.has(k))return false;seen.add(k);return true})}
function renderTemporaryCharacters(){let box=$('tempList');if(!box)return;box.innerHTML='';temporaryEntries().forEach(x=>{let row=document.createElement('div');row.className='temp-item';let cb=document.createElement('input');cb.type='checkbox';cb.value=characterKey(x.c);let open=document.createElement('button');open.type='button';open.className='temp-open';let im=document.createElement('img');im.src=x.c.imageUrl||'';let name=document.createElement('span');name.textContent=x.c.name||'';open.append(im,name);open.onclick=()=>openDetail(x.i,false,temporaryEntries().map(y=>y.i));let del=document.createElement('button');del.type='button';del.className='mini-reset danger temp-delete';del.textContent='キャラ削除';del.onclick=()=>{tempCharacters=tempCharacters.filter(k=>k!==characterKey(x.c));persistTemporaryCharacters()};row.append(cb,open,del);box.append(row)});$('tempEmpty').hidden=box.children.length>0}
function removeSelectedTemporary(){let values=[...document.querySelectorAll('#tempList input:checked')].map(x=>x.value),set=new Set(values);tempCharacters=tempCharacters.filter(x=>!set.has(x));persistTemporaryCharacters()}
function clearAllTemporary(){tempCharacters=[];persistTemporaryCharacters()}
function renderPickerTemporary(){let box=$('pickerTemporary');if(!box)return;box.innerHTML='';let list=pickerSource(temporaryEntries());$('pickerTemporarySection').hidden=!list.length;list.forEach(x=>box.append(card(x.c,x.i,true,null,true)))}
function addBorrowedSkill(role,c){borrowedSkills[role].push(c);borrowedEnabled[role].push(false);renderBorrowedSkills(role);calculate()}
function clearBorrowedSkills(role){borrowedSkills[role]=[];borrowedEnabled[role]=[];renderBorrowedSkills(role);calculate()}
function toggleBorrowedSkill(role,index){borrowedEnabled[role][index]=!borrowedEnabled[role][index];renderBorrowedSkills(role);calculate()}
function useAllBorrowed(role){borrowedEnabled[role]=borrowedSkills[role].map(()=>true);renderBorrowedSkills(role);calculate()}
function disableAllBorrowed(role){borrowedEnabled[role]=borrowedSkills[role].map(()=>false);renderBorrowedSkills(role);calculate()}
function deleteBorrowedSkill(role,index){borrowedSkills[role].splice(index,1);borrowedEnabled[role].splice(index,1);renderBorrowedSkills(role);calculate()}
function renderBorrowedSkills(role){let box=$(role+'BorrowedList'),list=borrowedSkills[role];while(borrowedEnabled[role].length<list.length)borrowedEnabled[role].push(false);borrowedEnabled[role].length=list.length;box.innerHTML='';list.forEach((c,i)=>{let row=document.createElement('div');row.className='borrowed-item';let span=document.createElement('span');span.textContent=(c.name||'')+'：'+(c.details?.skill||'スキルなし');let use=document.createElement('button');use.type='button';use.className='mini-reset borrowed-use'+(borrowedEnabled[role][i]?' active':'');use.textContent=borrowedEnabled[role][i]?'スキル解除':'スキル使用';use.onclick=()=>toggleBorrowedSkill(role,i);let del=document.createElement('button');del.type='button';del.className='mini-reset danger borrowed-delete';del.textContent='スキル削除';del.onclick=()=>deleteBorrowedSkill(role,i);row.append(span,use,del);box.append(row)});$(role+'BorrowedCount').textContent=list.length+'体';$(role+'BorrowedActions').hidden=!list.length}
function pickerSortCardLabel(c){let d=c.details||{},sort=$('pickerSort')?.value;if(!sort)return c.name||'';if(sort==='hp')return `HP ${Number(d.limitHp??d.hp??0).toLocaleString()}`;if(sort==='power')return `攻撃力 ${Number(d.limitPower??d.power??0).toLocaleString()}`;if(sort==='total')return `HP+攻撃力 ${(Number(d.limitHp??d.hp??0)+Number(d.limitPower??d.power??0)).toLocaleString()}`;if(sort==='cost')return `Cost ${Number(d.cost??0).toLocaleString()}`;if(sort==='skillTurn')return `スキルターン ${Number(d.skillTurn??0).toLocaleString()}`;if(sort==='rare')return `レア ${d.rare||''}`;return c.name||''}
function renderPickerFilterResults(){let section=$('pickerFilterResults'),active=pickerFiltersActive();section.hidden=!active;if(!active){$('pickerFilteredBox').innerHTML='';$('pickerFilteredCount').textContent='';return}let seen=new Set(),r=pickerFilterResults(pickerSource(results($('pickerSearch').value))).filter(x=>{let key=characterKey(x.c)||String(x.i);if(seen.has(key))return false;seen.add(key);return true}),box=$('pickerFilteredBox');$('pickerFilteredCount').textContent=`${r.length}件`;box.innerHTML='';r.forEach(x=>box.append(card(x.c,x.i,true,pickerSortCardLabel(x.c),true)))}
function ensurePickerTools(){let tools=$('pickerTools');if(tools.dataset.ready)return;tools.dataset.ready='1';$('pickerTemporaryToggle').onclick=()=>{let body=$('pickerTemporaryBody'),open=body.classList.toggle('open');$('pickerTemporaryToggle').querySelector('span').textContent=open?'▼':'▶'};tools.querySelectorAll('input,select').forEach(q=>q.oninput=renderPicker);$('pickerSort').addEventListener('change',()=>{if($('pickerSort').value==='skillTurn')$('pickerSortDirection').value='asc';renderPicker()});$('pickerCostMin').addEventListener('input',()=>{if($('pickerCostMax').value==='')$('pickerCostMax').value=$('pickerCostMin').value});tools.querySelectorAll('input[type=checkbox],input[type=radio]').forEach(q=>q.onchange=renderPicker);$('pickerFilterClear').onclick=()=>{tools.querySelectorAll('input[type=checkbox]').forEach(q=>q.checked=false);tools.querySelectorAll('input[type=number]').forEach(q=>q.value='');$('pickerAttrModeInclude').checked=true;$('pickerSort').value='';$('pickerSortDirection').value='desc';renderPicker()};for(let role of ['attacker','defender']){$(role+'UseAllBorrowed').onclick=()=>useAllBorrowed(role);$(role+'DisableAllBorrowed').onclick=()=>disableAllBorrowed(role);$(role+'ClearBorrowed').onclick=()=>clearBorrowedSkills(role)}renderBorrowedSkills('attacker');renderBorrowedSkills('defender')}
function pickerFiltersActive(){let t=$('pickerTools');return [...t.querySelectorAll('input[type=checkbox]')].some(q=>q.checked)||[...t.querySelectorAll('input[type=number]')].some(q=>q.value)||$('pickerSort').value}
function pickerFilterResults(base){let t=$('pickerTools');if(!t)return base;let vals=n=>[...t.querySelectorAll(`[name="${n}"]:checked`)].map(q=>q.value),attrs=vals('pickerAttribute'),rares=vals('pickerRare'),skills=vals('pickerSkill'),mode=t.querySelector('[name=pickerAttributeMode]:checked')?.value||'include',cmin=raw($('pickerCostMin').value),cmax=raw($('pickerCostMax').value),tmin=raw($('pickerTurnMin').value),tmax=raw($('pickerTurnMax').value),sort=$('pickerSort').value,dir=$('pickerSortDirection').value==='asc'?1:-1,rank={N:1,R:2,CR:3,ZR:4,MZR:5,'伝':6};let r=base.filter(x=>{let d=x.c.details||{},effects=d.skillEffects||[];return attributeMatches(d.attribute,attrs,mode)&&(!rares.length||rares.includes(d.rare))&&(!Number.isFinite(cmin)||Number(d.cost)>=cmin)&&(!Number.isFinite(cmax)||Number(d.cost)<=cmax)&&(!skills.length||skills.some(v=>effects.some(e=>en(e)===v)))&&(!Number.isFinite(tmin)||Number(d.skillTurn)>=tmin)&&(!Number.isFinite(tmax)||Number(d.skillTurn)<=tmax)});if(sort==='skillTurn')r.sort(compareSkillTurn);else if(sort)r.sort((a,b)=>{let ad=a.c.details||{},bd=b.c.details||{},v=d=>sort==='total'?Number(d.limitHp??d.hp??0)+Number(d.limitPower??d.power??0):sort==='rare'?(rank[d.rare]||0):Number(d[sort]??0);return(v(ad)-v(bd))*dir||characterIdOrder(a)-characterIdOrder(b)||a.i-b.i});return r}
