/* Cooperative proposal worker build 20260920-364 */
let stopped=false,paused=false,initialized=false,workerIndex=0,currentJob=null;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitWhilePaused(){while(paused&&!stopped)await sleep(40)}
function flushItems(job,type){if(!job.items.length)return;postMessage(type==='stage'?{type:'stageItems',jobId:job.jobId,items:job.items.splice(0),passed:job.passed}:{type:'confirmedItems',jobId:job.jobId,confirmed:job.items.splice(0),passed:job.passed})}
async function runJob(m){stopped=false;self.coopEnemies=m.enemies;self.coopDecks=m.decks;self.coopVisibleRows=m.visibleRows;self.coopDetailMode=!!m.detailMode;self.coopProposalTargetDecks=m.targetDecks;self.coopProposalEnemySecondFixed=!!m.enemySecondFixed;self.COOP_DAMAGE_BASE=m.constants.damageBase;self.coopProposalDamageScale=Number(m.constants.damageScale??1);self.coopProposalOrderCache.clear();self.coopProposalManualCertainCache.clear();const job={jobId:m.jobId,prefixIds:m.prefixIds||[],candidateIds:m.candidateIds||[],items:[],checked:0,passed:0,last:performance.now(),index:0,type:m.type};currentJob=job;
 if(m.type==='stage'){const total=job.prefixIds.length*job.candidateIds.length;while(job.index<total&&!stopped){await waitWhilePaused();if(stopped)break;let end=Math.min(total,job.index+250);for(;job.index<end&&!stopped;job.index++){let p=Math.floor(job.index/job.candidateIds.length),c=job.index%job.candidateIds.length,ids=job.prefixIds[p].slice();ids[m.slot]=job.candidateIds[c];let deck=ids.map(coopFindCharacter),item=coopProposalPrefixLayerEvaluation(deck,m.slot,m.targetDecks);if(item){job.items.push({ids:coopProposalDeckIds(item.deck)});job.passed++}job.checked++}if(job.items.length>=3000)flushItems(job,'stage');let now=performance.now();if(job.checked%1000===0||now-job.last>=300){postMessage({type:'progress',jobId:job.jobId,checked:job.checked,passed:job.passed,confirmed:job.passed});job.last=now}await sleep(0)}if(!stopped){flushItems(job,'stage');postMessage({type:'stageDone',jobId:job.jobId,checked:job.checked,passed:job.passed,items:[]})}}
 else{const total=job.candidateIds.length;while(job.index<total&&!stopped){await waitWhilePaused();if(stopped)break;let end=Math.min(total,job.index+100);for(;job.index<end&&!stopped;job.index++){let ids=job.candidateIds[job.index],deck=ids.map(coopFindCharacter);if(coopProposalWorks(deck,m.targetDecks)){job.items.push({ids:ids.slice(),repeats:m.targetDecks,overkillRate:0});job.passed++}job.checked++}if(job.items.length>=3000)flushItems(job,'start');let now=performance.now();if(job.checked%1000===0||now-job.last>=300){postMessage({type:'progress',jobId:job.jobId,checked:job.checked,passed:job.passed,confirmed:job.passed});job.last=now}await sleep(0)}if(!stopped){flushItems(job,'start');postMessage({type:'done',jobId:job.jobId,checked:job.checked,passed:job.passed,confirmed:[]})}}currentJob=null}
self.onmessage=e=>{const m=e.data||{};if(m.type==='pause'){paused=true;return}if(m.type==='resume'){paused=false;return}if(m.type==='cancel'){stopped=true;paused=false;return}try{if(m.type==='init'){self.chars=m.chars||[];workerIndex=m.workerIndex||0;self.ATTRS=m.constants.ATTRS;self.MATCH=m.constants.MATCH;self.COOP_LAYER_MULTIPLIERS=m.constants.layerMultipliers;self.COOP_DAMAGE_BASE=m.constants.damageBase;self.coopProposalDamageScale=Number(m.constants.damageScale??1);self.COOP_SLOTS=5;self.COOP_MAX_ROWS=5;self.coopProposalOrderCache=new Map();self.coopProposalManualCertainCache=new Map();(0,eval)(m.engineSource);self.characterById=new Map(self.chars.map(c=>[coopCharacterKey(c),c]));self.coopFindCharacter=key=>self.characterById.get(String(key))||null;initialized=true;postMessage({type:'initialized',workerIndex});return}if(!initialized||!['start','stage'].includes(m.type)||currentJob)return;runJob(m).catch(error=>postMessage({type:'error',jobId:m.jobId,message:String(error&&error.stack||error)}))}catch(error){postMessage({type:'error',jobId:m.jobId,message:String(error&&error.stack||error)})}};
