/* Cooperative proposal worker build 20260920-335 */
let stopped=false,initialized=false,workerIndex=0;
self.onmessage=e=>{const m=e.data||{};if(m.type==='cancel'){stopped=true;return}try{
if(m.type==='init'){self.chars=m.chars||[];workerIndex=m.workerIndex||0;self.ATTRS=m.constants.ATTRS;self.MATCH=m.constants.MATCH;self.COOP_LAYER_MULTIPLIERS=m.constants.layerMultipliers;self.COOP_DAMAGE_BASE=m.constants.damageBase;self.coopProposalDamageScale=Number(m.constants.damageScale??1);self.COOP_SLOTS=5;self.COOP_MAX_ROWS=5;self.coopProposalOrderCache=new Map();self.coopProposalManualCertainCache=new Map();(0,eval)(m.engineSource);self.characterById=new Map(self.chars.map(c=>[coopCharacterKey(c),c]));self.coopFindCharacter=key=>self.characterById.get(String(key))||null;initialized=true;postMessage({type:'initialized',workerIndex});return}
if(!initialized||!['start','stage'].includes(m.type))return;stopped=false;self.coopEnemies=m.enemies;self.coopDecks=m.decks;self.coopVisibleRows=m.visibleRows;self.coopDetailMode=!!m.detailMode;self.coopProposalTargetDecks=m.targetDecks;self.coopProposalEnemySecondFixed=!!m.enemySecondFixed;self.COOP_DAMAGE_BASE=m.constants.damageBase;self.coopProposalDamageScale=Number(m.constants.damageScale??1);self.coopProposalOrderCache.clear();self.coopProposalManualCertainCache.clear();
const jobId=m.jobId,prefixIds=m.prefixIds||[],candidateIds=m.candidateIds||[],items=[];let checked=0,passed=0,last=performance.now();const flush=type=>{if(!items.length)return;postMessage(type==='stage'?{type:'stageItems',jobId,items:items.splice(0),passed}:{type:'confirmedItems',jobId,confirmed:items.splice(0),passed})};
if(m.type==='stage'){const total=prefixIds.length*candidateIds.length;for(let flat=0;flat<total&&!stopped;flat++){let prefixIndex=Math.floor(flat/candidateIds.length),candidateIndex=flat%candidateIds.length,ids=prefixIds[prefixIndex].slice();ids[m.slot]=candidateIds[candidateIndex];let deck=ids.map(coopFindCharacter),item=coopProposalPrefixLayerEvaluation(deck,m.slot,m.targetDecks);if(item){items.push({ids:coopProposalDeckIds(item.deck)});passed++}checked++;if(items.length>=3000)flush('stage');let now=performance.now();if(checked%1000===0||now-last>=300){postMessage({type:'progress',jobId,checked,passed,confirmed:passed});last=now}}flush('stage');postMessage({type:'stageDone',jobId,checked,passed,items:[]})
}else{for(let flat=0;flat<candidateIds.length&&!stopped;flat++){let ids=candidateIds[flat],deck=ids.map(coopFindCharacter);if(coopProposalWorks(deck,m.targetDecks)){items.push({ids:ids.slice(),repeats:m.targetDecks,overkillRate:0});passed++}checked++;if(items.length>=3000)flush('start');let now=performance.now();if(checked%1000===0||now-last>=300){postMessage({type:'progress',jobId,checked,passed,confirmed:passed});last=now}}flush('start');postMessage({type:'done',jobId,checked,passed,confirmed:[]})}
}catch(error){postMessage({type:'error',jobId:e.data?.jobId,message:String(error&&error.stack||error)})}};
